//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.03.06 at 01:00:16 PM EST 
//


package uk.ac.ebi.interpro.resources.schemas.interproscan5;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for EntryTypeType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="EntryTypeType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="ACTIVE_SITE"/>
 *     &lt;enumeration value="BINDING_SITE"/>
 *     &lt;enumeration value="CONSERVED_SITE"/>
 *     &lt;enumeration value="DOMAIN"/>
 *     &lt;enumeration value="FAMILY"/>
 *     &lt;enumeration value="PTM"/>
 *     &lt;enumeration value="REPEAT"/>
 *     &lt;enumeration value="UNKNOWN"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "EntryTypeType")
@XmlEnum
public enum EntryTypeType {

    ACTIVE_SITE,
    BINDING_SITE,
    CONSERVED_SITE,
    DOMAIN,
    FAMILY,
    PTM,
    REPEAT,
    UNKNOWN;

    public String value() {
        return name();
    }

    public static EntryTypeType fromValue(String v) {
        return valueOf(v);
    }

}
