//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.03.06 at 01:00:16 PM EST 
//


package uk.ac.ebi.interpro.resources.schemas.interproscan5;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for HmmerLocationType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="HmmerLocationType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.ebi.ac.uk/interpro/resources/schemas/interproscan5}LocationType">
 *       &lt;sequence>
 *       &lt;/sequence>
 *       &lt;attribute name="score" use="required" type="{http://www.w3.org/2001/XMLSchema}double" />
 *       &lt;attribute name="evalue" use="required" type="{http://www.w3.org/2001/XMLSchema}double" />
 *       &lt;attribute name="hmm-start" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="hmm-end" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="hmm-length" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "HmmerLocationType")
@XmlSeeAlso({
    Hmmer2LocationType.class,
    Hmmer3LocationType.class
})
public abstract class HmmerLocationType
    extends LocationType
{

    @XmlAttribute(name = "score", required = true)
    protected double score;
    @XmlAttribute(name = "evalue", required = true)
    protected double evalue;
    @XmlAttribute(name = "hmm-start", required = true)
    protected int hmmStart;
    @XmlAttribute(name = "hmm-end", required = true)
    protected int hmmEnd;
    @XmlAttribute(name = "hmm-length", required = true)
    protected int hmmLength;

    /**
     * Gets the value of the score property.
     * 
     */
    public double getScore() {
        return score;
    }

    /**
     * Sets the value of the score property.
     * 
     */
    public void setScore(double value) {
        this.score = value;
    }

    /**
     * Gets the value of the evalue property.
     * 
     */
    public double getEvalue() {
        return evalue;
    }

    /**
     * Sets the value of the evalue property.
     * 
     */
    public void setEvalue(double value) {
        this.evalue = value;
    }

    /**
     * Gets the value of the hmmStart property.
     * 
     */
    public int getHmmStart() {
        return hmmStart;
    }

    /**
     * Sets the value of the hmmStart property.
     * 
     */
    public void setHmmStart(int value) {
        this.hmmStart = value;
    }

    /**
     * Gets the value of the hmmEnd property.
     * 
     */
    public int getHmmEnd() {
        return hmmEnd;
    }

    /**
     * Sets the value of the hmmEnd property.
     * 
     */
    public void setHmmEnd(int value) {
        this.hmmEnd = value;
    }

    /**
     * Gets the value of the hmmLength property.
     * 
     */
    public int getHmmLength() {
        return hmmLength;
    }

    /**
     * Sets the value of the hmmLength property.
     * 
     */
    public void setHmmLength(int value) {
        this.hmmLength = value;
    }

}
