//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.03.06 at 01:00:16 PM EST 
//


package uk.ac.ebi.interpro.resources.schemas.interproscan5;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for matchesType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="matchesType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="coils-match" type="{http://www.ebi.ac.uk/interpro/resources/schemas/interproscan5}CoilsMatchType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="fingerprints-match" type="{http://www.ebi.ac.uk/interpro/resources/schemas/interproscan5}FingerPrintsMatchType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="hmmer2-match" type="{http://www.ebi.ac.uk/interpro/resources/schemas/interproscan5}Hmmer2MatchType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="hmmer3-match" type="{http://www.ebi.ac.uk/interpro/resources/schemas/interproscan5}Hmmer3MatchType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="panther-match" type="{http://www.ebi.ac.uk/interpro/resources/schemas/interproscan5}PantherMatchType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="patternscan-match" type="{http://www.ebi.ac.uk/interpro/resources/schemas/interproscan5}PatternScanMatchType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="phobius-match" type="{http://www.ebi.ac.uk/interpro/resources/schemas/interproscan5}PhobiusMatchType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="blastprodom-match" type="{http://www.ebi.ac.uk/interpro/resources/schemas/interproscan5}BlastProDomMatchType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="profilescan-match" type="{http://www.ebi.ac.uk/interpro/resources/schemas/interproscan5}ProfileScanMatchType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="signalp-match" type="{http://www.ebi.ac.uk/interpro/resources/schemas/interproscan5}SignalPMatchType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="superfamilyhmmer3-match" type="{http://www.ebi.ac.uk/interpro/resources/schemas/interproscan5}SuperFamilyHmmer3MatchType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="tmhmm-match" type="{http://www.ebi.ac.uk/interpro/resources/schemas/interproscan5}TMHMMMatchType" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "matchesType", propOrder = {
    "coilsMatch",
    "fingerprintsMatch",
    "hmmer2Match",
    "hmmer3Match",
    "pantherMatch",
    "patternscanMatch",
    "phobiusMatch",
    "blastprodomMatch",
    "profilescanMatch",
    "signalpMatch",
    "superfamilyhmmer3Match",
    "tmhmmMatch"
})
public class MatchesType {

    @XmlElement(name = "coils-match")
    protected List<CoilsMatchType> coilsMatch;
    @XmlElement(name = "fingerprints-match")
    protected List<FingerPrintsMatchType> fingerprintsMatch;
    @XmlElement(name = "hmmer2-match")
    protected List<Hmmer2MatchType> hmmer2Match;
    @XmlElement(name = "hmmer3-match")
    protected List<Hmmer3MatchType> hmmer3Match;
    @XmlElement(name = "panther-match")
    protected List<PantherMatchType> pantherMatch;
    @XmlElement(name = "patternscan-match")
    protected List<PatternScanMatchType> patternscanMatch;
    @XmlElement(name = "phobius-match")
    protected List<PhobiusMatchType> phobiusMatch;
    @XmlElement(name = "blastprodom-match")
    protected List<BlastProDomMatchType> blastprodomMatch;
    @XmlElement(name = "profilescan-match")
    protected List<ProfileScanMatchType> profilescanMatch;
    @XmlElement(name = "signalp-match")
    protected List<SignalPMatchType> signalpMatch;
    @XmlElement(name = "superfamilyhmmer3-match")
    protected List<SuperFamilyHmmer3MatchType> superfamilyhmmer3Match;
    @XmlElement(name = "tmhmm-match")
    protected List<TMHMMMatchType> tmhmmMatch;

    /**
     * Gets the value of the coilsMatch property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the coilsMatch property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCoilsMatch().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CoilsMatchType }
     * 
     * 
     */
    public List<CoilsMatchType> getCoilsMatch() {
        if (coilsMatch == null) {
            coilsMatch = new ArrayList<CoilsMatchType>();
        }
        return this.coilsMatch;
    }

    /**
     * Gets the value of the fingerprintsMatch property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the fingerprintsMatch property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getFingerprintsMatch().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link FingerPrintsMatchType }
     * 
     * 
     */
    public List<FingerPrintsMatchType> getFingerprintsMatch() {
        if (fingerprintsMatch == null) {
            fingerprintsMatch = new ArrayList<FingerPrintsMatchType>();
        }
        return this.fingerprintsMatch;
    }

    /**
     * Gets the value of the hmmer2Match property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the hmmer2Match property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getHmmer2Match().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Hmmer2MatchType }
     * 
     * 
     */
    public List<Hmmer2MatchType> getHmmer2Match() {
        if (hmmer2Match == null) {
            hmmer2Match = new ArrayList<Hmmer2MatchType>();
        }
        return this.hmmer2Match;
    }

    /**
     * Gets the value of the hmmer3Match property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the hmmer3Match property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getHmmer3Match().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Hmmer3MatchType }
     * 
     * 
     */
    public List<Hmmer3MatchType> getHmmer3Match() {
        if (hmmer3Match == null) {
            hmmer3Match = new ArrayList<Hmmer3MatchType>();
        }
        return this.hmmer3Match;
    }

    /**
     * Gets the value of the pantherMatch property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the pantherMatch property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPantherMatch().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link PantherMatchType }
     * 
     * 
     */
    public List<PantherMatchType> getPantherMatch() {
        if (pantherMatch == null) {
            pantherMatch = new ArrayList<PantherMatchType>();
        }
        return this.pantherMatch;
    }

    /**
     * Gets the value of the patternscanMatch property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the patternscanMatch property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPatternscanMatch().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link PatternScanMatchType }
     * 
     * 
     */
    public List<PatternScanMatchType> getPatternscanMatch() {
        if (patternscanMatch == null) {
            patternscanMatch = new ArrayList<PatternScanMatchType>();
        }
        return this.patternscanMatch;
    }

    /**
     * Gets the value of the phobiusMatch property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the phobiusMatch property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPhobiusMatch().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link PhobiusMatchType }
     * 
     * 
     */
    public List<PhobiusMatchType> getPhobiusMatch() {
        if (phobiusMatch == null) {
            phobiusMatch = new ArrayList<PhobiusMatchType>();
        }
        return this.phobiusMatch;
    }

    /**
     * Gets the value of the blastprodomMatch property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the blastprodomMatch property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getBlastprodomMatch().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link BlastProDomMatchType }
     * 
     * 
     */
    public List<BlastProDomMatchType> getBlastprodomMatch() {
        if (blastprodomMatch == null) {
            blastprodomMatch = new ArrayList<BlastProDomMatchType>();
        }
        return this.blastprodomMatch;
    }

    /**
     * Gets the value of the profilescanMatch property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the profilescanMatch property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getProfilescanMatch().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ProfileScanMatchType }
     * 
     * 
     */
    public List<ProfileScanMatchType> getProfilescanMatch() {
        if (profilescanMatch == null) {
            profilescanMatch = new ArrayList<ProfileScanMatchType>();
        }
        return this.profilescanMatch;
    }

    /**
     * Gets the value of the signalpMatch property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the signalpMatch property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSignalpMatch().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SignalPMatchType }
     * 
     * 
     */
    public List<SignalPMatchType> getSignalpMatch() {
        if (signalpMatch == null) {
            signalpMatch = new ArrayList<SignalPMatchType>();
        }
        return this.signalpMatch;
    }

    /**
     * Gets the value of the superfamilyhmmer3Match property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the superfamilyhmmer3Match property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSuperfamilyhmmer3Match().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SuperFamilyHmmer3MatchType }
     * 
     * 
     */
    public List<SuperFamilyHmmer3MatchType> getSuperfamilyhmmer3Match() {
        if (superfamilyhmmer3Match == null) {
            superfamilyhmmer3Match = new ArrayList<SuperFamilyHmmer3MatchType>();
        }
        return this.superfamilyhmmer3Match;
    }

    /**
     * Gets the value of the tmhmmMatch property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the tmhmmMatch property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTmhmmMatch().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TMHMMMatchType }
     * 
     * 
     */
    public List<TMHMMMatchType> getTmhmmMatch() {
        if (tmhmmMatch == null) {
            tmhmmMatch = new ArrayList<TMHMMMatchType>();
        }
        return this.tmhmmMatch;
    }

}
