//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.03.06 at 01:00:16 PM EST 
//


package uk.ac.ebi.interpro.resources.schemas.interproscan5;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the uk.ac.ebi.interpro.resources.schemas.interproscan5 package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Signature_QNAME = new QName("http://www.ebi.ac.uk/interpro/resources/schemas/interproscan5", "signature");
    private final static QName _SignatureLibraryRelease_QNAME = new QName("http://www.ebi.ac.uk/interpro/resources/schemas/interproscan5", "signature-library-release");
    private final static QName _NucleotideSequence_QNAME = new QName("http://www.ebi.ac.uk/interpro/resources/schemas/interproscan5", "nucleotide-sequence");
    private final static QName _NucleotideSequenceMatches_QNAME = new QName("http://www.ebi.ac.uk/interpro/resources/schemas/interproscan5", "nucleotide-sequence-matches");
    private final static QName _Orf_QNAME = new QName("http://www.ebi.ac.uk/interpro/resources/schemas/interproscan5", "orf");
    private final static QName _Entry_QNAME = new QName("http://www.ebi.ac.uk/interpro/resources/schemas/interproscan5", "entry");
    private final static QName _Protein_QNAME = new QName("http://www.ebi.ac.uk/interpro/resources/schemas/interproscan5", "protein");
    private final static QName _InterproRelease_QNAME = new QName("http://www.ebi.ac.uk/interpro/resources/schemas/interproscan5", "interpro-release");
    private final static QName _ProteinMatches_QNAME = new QName("http://www.ebi.ac.uk/interpro/resources/schemas/interproscan5", "protein-matches");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: uk.ac.ebi.interpro.resources.schemas.interproscan5
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ProteinMatchesType }
     * 
     */
    public ProteinMatchesType createProteinMatchesType() {
        return new ProteinMatchesType();
    }

    /**
     * Create an instance of {@link ReleaseType }
     * 
     */
    public ReleaseType createReleaseType() {
        return new ReleaseType();
    }

    /**
     * Create an instance of {@link ProteinType }
     * 
     */
    public ProteinType createProteinType() {
        return new ProteinType();
    }

    /**
     * Create an instance of {@link EntryType }
     * 
     */
    public EntryType createEntryType() {
        return new EntryType();
    }

    /**
     * Create an instance of {@link OrfType }
     * 
     */
    public OrfType createOrfType() {
        return new OrfType();
    }

    /**
     * Create an instance of {@link NucleicAcidMatchesType }
     * 
     */
    public NucleicAcidMatchesType createNucleicAcidMatchesType() {
        return new NucleicAcidMatchesType();
    }

    /**
     * Create an instance of {@link NucleotideType }
     * 
     */
    public NucleotideType createNucleotideType() {
        return new NucleotideType();
    }

    /**
     * Create an instance of {@link SignatureLibraryReleaseType }
     * 
     */
    public SignatureLibraryReleaseType createSignatureLibraryReleaseType() {
        return new SignatureLibraryReleaseType();
    }

    /**
     * Create an instance of {@link SignatureType }
     * 
     */
    public SignatureType createSignatureType() {
        return new SignatureType();
    }

    /**
     * Create an instance of {@link TMHMMMatchType }
     * 
     */
    public TMHMMMatchType createTMHMMMatchType() {
        return new TMHMMMatchType();
    }

    /**
     * Create an instance of {@link Location }
     * 
     */
    public Location createLocation() {
        return new Location();
    }

    /**
     * Create an instance of {@link PersistenceConversion }
     * 
     */
    public PersistenceConversion createPersistenceConversion() {
        return new PersistenceConversion();
    }

    /**
     * Create an instance of {@link SignalPLocationType }
     * 
     */
    public SignalPLocationType createSignalPLocationType() {
        return new SignalPLocationType();
    }

    /**
     * Create an instance of {@link FingerPrintsLocationType }
     * 
     */
    public FingerPrintsLocationType createFingerPrintsLocationType() {
        return new FingerPrintsLocationType();
    }

    /**
     * Create an instance of {@link BlastProDomMatchType }
     * 
     */
    public BlastProDomMatchType createBlastProDomMatchType() {
        return new BlastProDomMatchType();
    }

    /**
     * Create an instance of {@link PhobiusLocationType }
     * 
     */
    public PhobiusLocationType createPhobiusLocationType() {
        return new PhobiusLocationType();
    }

    /**
     * Create an instance of {@link NucleotideSequenceType }
     * 
     */
    public NucleotideSequenceType createNucleotideSequenceType() {
        return new NucleotideSequenceType();
    }

    /**
     * Create an instance of {@link PatternScanLocationType }
     * 
     */
    public PatternScanLocationType createPatternScanLocationType() {
        return new PatternScanLocationType();
    }

    /**
     * Create an instance of {@link ModelsType }
     * 
     */
    public ModelsType createModelsType() {
        return new ModelsType();
    }

    /**
     * Create an instance of {@link SuperFamilyHmmer3LocationType }
     * 
     */
    public SuperFamilyHmmer3LocationType createSuperFamilyHmmer3LocationType() {
        return new SuperFamilyHmmer3LocationType();
    }

    /**
     * Create an instance of {@link CoilsLocationType }
     * 
     */
    public CoilsLocationType createCoilsLocationType() {
        return new CoilsLocationType();
    }

    /**
     * Create an instance of {@link PatternScanMatchType }
     * 
     */
    public PatternScanMatchType createPatternScanMatchType() {
        return new PatternScanMatchType();
    }

    /**
     * Create an instance of {@link GoXrefType }
     * 
     */
    public GoXrefType createGoXrefType() {
        return new GoXrefType();
    }

    /**
     * Create an instance of {@link ProfileScanLocationType }
     * 
     */
    public ProfileScanLocationType createProfileScanLocationType() {
        return new ProfileScanLocationType();
    }

    /**
     * Create an instance of {@link LocationsType }
     * 
     */
    public LocationsType createLocationsType() {
        return new LocationsType();
    }

    /**
     * Create an instance of {@link SuperMatchType }
     * 
     */
    public SuperMatchType createSuperMatchType() {
        return new SuperMatchType();
    }

    /**
     * Create an instance of {@link SequenceType }
     * 
     */
    public SequenceType createSequenceType() {
        return new SequenceType();
    }

    /**
     * Create an instance of {@link FingerPrintsMatchType }
     * 
     */
    public FingerPrintsMatchType createFingerPrintsMatchType() {
        return new FingerPrintsMatchType();
    }

    /**
     * Create an instance of {@link SignalPMatchType }
     * 
     */
    public SignalPMatchType createSignalPMatchType() {
        return new SignalPMatchType();
    }

    /**
     * Create an instance of {@link Hmmer2MatchType }
     * 
     */
    public Hmmer2MatchType createHmmer2MatchType() {
        return new Hmmer2MatchType();
    }

    /**
     * Create an instance of {@link SuperFamilyHmmer3MatchType }
     * 
     */
    public SuperFamilyHmmer3MatchType createSuperFamilyHmmer3MatchType() {
        return new SuperFamilyHmmer3MatchType();
    }

    /**
     * Create an instance of {@link PantherLocationType }
     * 
     */
    public PantherLocationType createPantherLocationType() {
        return new PantherLocationType();
    }

    /**
     * Create an instance of {@link PantherMatchType }
     * 
     */
    public PantherMatchType createPantherMatchType() {
        return new PantherMatchType();
    }

    /**
     * Create an instance of {@link Hmmer2LocationType }
     * 
     */
    public Hmmer2LocationType createHmmer2LocationType() {
        return new Hmmer2LocationType();
    }

    /**
     * Create an instance of {@link NucleotideSequenceXrefType }
     * 
     */
    public NucleotideSequenceXrefType createNucleotideSequenceXrefType() {
        return new NucleotideSequenceXrefType();
    }

    /**
     * Create an instance of {@link BlastProDomLocationType }
     * 
     */
    public BlastProDomLocationType createBlastProDomLocationType() {
        return new BlastProDomLocationType();
    }

    /**
     * Create an instance of {@link CoilsMatchType }
     * 
     */
    public CoilsMatchType createCoilsMatchType() {
        return new CoilsMatchType();
    }

    /**
     * Create an instance of {@link Hmmer3MatchType }
     * 
     */
    public Hmmer3MatchType createHmmer3MatchType() {
        return new Hmmer3MatchType();
    }

    /**
     * Create an instance of {@link Hmmer3LocationType }
     * 
     */
    public Hmmer3LocationType createHmmer3LocationType() {
        return new Hmmer3LocationType();
    }

    /**
     * Create an instance of {@link MatchesType }
     * 
     */
    public MatchesType createMatchesType() {
        return new MatchesType();
    }

    /**
     * Create an instance of {@link ModelType }
     * 
     */
    public ModelType createModelType() {
        return new ModelType();
    }

    /**
     * Create an instance of {@link PathwayXrefType }
     * 
     */
    public PathwayXrefType createPathwayXrefType() {
        return new PathwayXrefType();
    }

    /**
     * Create an instance of {@link TMHMMLocationType }
     * 
     */
    public TMHMMLocationType createTMHMMLocationType() {
        return new TMHMMLocationType();
    }

    /**
     * Create an instance of {@link SignatureXrefType }
     * 
     */
    public SignatureXrefType createSignatureXrefType() {
        return new SignatureXrefType();
    }

    /**
     * Create an instance of {@link ProteinXrefType }
     * 
     */
    public ProteinXrefType createProteinXrefType() {
        return new ProteinXrefType();
    }

    /**
     * Create an instance of {@link ProfileScanMatchType }
     * 
     */
    public ProfileScanMatchType createProfileScanMatchType() {
        return new ProfileScanMatchType();
    }

    /**
     * Create an instance of {@link PhobiusMatchType }
     * 
     */
    public PhobiusMatchType createPhobiusMatchType() {
        return new PhobiusMatchType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SignatureType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ebi.ac.uk/interpro/resources/schemas/interproscan5", name = "signature")
    public JAXBElement<SignatureType> createSignature(SignatureType value) {
        return new JAXBElement<SignatureType>(_Signature_QNAME, SignatureType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SignatureLibraryReleaseType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ebi.ac.uk/interpro/resources/schemas/interproscan5", name = "signature-library-release")
    public JAXBElement<SignatureLibraryReleaseType> createSignatureLibraryRelease(SignatureLibraryReleaseType value) {
        return new JAXBElement<SignatureLibraryReleaseType>(_SignatureLibraryRelease_QNAME, SignatureLibraryReleaseType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link NucleotideType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ebi.ac.uk/interpro/resources/schemas/interproscan5", name = "nucleotide-sequence")
    public JAXBElement<NucleotideType> createNucleotideSequence(NucleotideType value) {
        return new JAXBElement<NucleotideType>(_NucleotideSequence_QNAME, NucleotideType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link NucleicAcidMatchesType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ebi.ac.uk/interpro/resources/schemas/interproscan5", name = "nucleotide-sequence-matches")
    public JAXBElement<NucleicAcidMatchesType> createNucleotideSequenceMatches(NucleicAcidMatchesType value) {
        return new JAXBElement<NucleicAcidMatchesType>(_NucleotideSequenceMatches_QNAME, NucleicAcidMatchesType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link OrfType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ebi.ac.uk/interpro/resources/schemas/interproscan5", name = "orf")
    public JAXBElement<OrfType> createOrf(OrfType value) {
        return new JAXBElement<OrfType>(_Orf_QNAME, OrfType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link EntryType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ebi.ac.uk/interpro/resources/schemas/interproscan5", name = "entry")
    public JAXBElement<EntryType> createEntry(EntryType value) {
        return new JAXBElement<EntryType>(_Entry_QNAME, EntryType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ProteinType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ebi.ac.uk/interpro/resources/schemas/interproscan5", name = "protein")
    public JAXBElement<ProteinType> createProtein(ProteinType value) {
        return new JAXBElement<ProteinType>(_Protein_QNAME, ProteinType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ReleaseType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ebi.ac.uk/interpro/resources/schemas/interproscan5", name = "interpro-release")
    public JAXBElement<ReleaseType> createInterproRelease(ReleaseType value) {
        return new JAXBElement<ReleaseType>(_InterproRelease_QNAME, ReleaseType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ProteinMatchesType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ebi.ac.uk/interpro/resources/schemas/interproscan5", name = "protein-matches")
    public JAXBElement<ProteinMatchesType> createProteinMatches(ProteinMatchesType value) {
        return new JAXBElement<ProteinMatchesType>(_ProteinMatches_QNAME, ProteinMatchesType.class, null, value);
    }

}
