//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.03.06 at 01:00:16 PM EST 
//


package uk.ac.ebi.interpro.resources.schemas.interproscan5;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for PhobiusFeatureType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="PhobiusFeatureType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="SIGNAL_PEPTIDE"/>
 *     &lt;enumeration value="CYTOPLASMIC_DOMAIN"/>
 *     &lt;enumeration value="NON_CYTOPLASMIC_DOMAIN"/>
 *     &lt;enumeration value="TRANSMEMBRANE"/>
 *     &lt;enumeration value="SIGNAL_PEPTIDE_N_REGION"/>
 *     &lt;enumeration value="SIGNAL_PEPTIDE_H_REGION"/>
 *     &lt;enumeration value="SIGNAL_PEPTIDE_C_REGION"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "PhobiusFeatureType")
@XmlEnum
public enum PhobiusFeatureType {

    SIGNAL_PEPTIDE,
    CYTOPLASMIC_DOMAIN,
    NON_CYTOPLASMIC_DOMAIN,
    TRANSMEMBRANE,
    SIGNAL_PEPTIDE_N_REGION,
    SIGNAL_PEPTIDE_H_REGION,
    SIGNAL_PEPTIDE_C_REGION;

    public String value() {
        return name();
    }

    public static PhobiusFeatureType fromValue(String v) {
        return valueOf(v);
    }

}
