
package au.edu.unimelb.plantcell.servers.nectar.estscan;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "ESTScanService", targetNamespace = "http://nectar.plantcell.unimelb.edu.au", wsdlLocation = "file:/C:/Users/andrew.cassin/AppData/Local/Temp/tempdir8562679003958243621.tmp/ESTScanService_1.wsdl")
public class ESTScanService
    extends Service
{

    private final static URL ESTSCANSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(au.edu.unimelb.plantcell.servers.nectar.estscan.ESTScanService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = au.edu.unimelb.plantcell.servers.nectar.estscan.ESTScanService.class.getResource(".");
            url = new URL(baseUrl, "file:/C:/Users/andrew.cassin/AppData/Local/Temp/tempdir8562679003958243621.tmp/ESTScanService_1.wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'file:/C:/Users/andrew.cassin/AppData/Local/Temp/tempdir8562679003958243621.tmp/ESTScanService_1.wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        ESTSCANSERVICE_WSDL_LOCATION = url;
    }

    public ESTScanService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ESTScanService() {
        super(ESTSCANSERVICE_WSDL_LOCATION, new QName("http://nectar.plantcell.unimelb.edu.au", "ESTScanService"));
    }

    /**
     * 
     * @return
     *     returns ESTScanServicePortType
     */
    @WebEndpoint(name = "ESTScanServiceHttpSoap11Endpoint")
    public ESTScanServicePortType getESTScanServiceHttpSoap11Endpoint() {
        return super.getPort(new QName("http://nectar.plantcell.unimelb.edu.au", "ESTScanServiceHttpSoap11Endpoint"), ESTScanServicePortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ESTScanServicePortType
     */
    @WebEndpoint(name = "ESTScanServiceHttpSoap11Endpoint")
    public ESTScanServicePortType getESTScanServiceHttpSoap11Endpoint(WebServiceFeature... features) {
        return super.getPort(new QName("http://nectar.plantcell.unimelb.edu.au", "ESTScanServiceHttpSoap11Endpoint"), ESTScanServicePortType.class, features);
    }

}
