
package au.edu.unimelb.plantcell.servers.netphos;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "NetPhosService", targetNamespace = "http://nectar.plantcell.unimelb.edu.au", wsdlLocation = "http://115.146.93.92:8080/production/services/NetPhosService?wsdl")
public class NetPhosService
    extends Service
{

    private final static URL NETPHOSSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(au.edu.unimelb.plantcell.servers.netphos.NetPhosService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = au.edu.unimelb.plantcell.servers.netphos.NetPhosService.class.getResource(".");
            url = new URL(baseUrl, "http://115.146.93.92:8080/production/services/NetPhosService?wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://115.146.93.92:8080/production/services/NetPhosService?wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        NETPHOSSERVICE_WSDL_LOCATION = url;
    }

    public NetPhosService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public NetPhosService() {
        super(NETPHOSSERVICE_WSDL_LOCATION, new QName("http://nectar.plantcell.unimelb.edu.au", "NetPhosService"));
    }

    /**
     * 
     * @return
     *     returns NetPhosServicePortType
     */
    @WebEndpoint(name = "NetPhosServiceHttpSoap11Endpoint")
    public NetPhosServicePortType getNetPhosServiceHttpSoap11Endpoint() {
        return super.getPort(new QName("http://nectar.plantcell.unimelb.edu.au", "NetPhosServiceHttpSoap11Endpoint"), NetPhosServicePortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns NetPhosServicePortType
     */
    @WebEndpoint(name = "NetPhosServiceHttpSoap11Endpoint")
    public NetPhosServicePortType getNetPhosServiceHttpSoap11Endpoint(WebServiceFeature... features) {
        return super.getPort(new QName("http://nectar.plantcell.unimelb.edu.au", "NetPhosServiceHttpSoap11Endpoint"), NetPhosServicePortType.class, features);
    }

}
