
package au.edu.unimelb.plantcell.io.ws.biomart.soap;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * BioMart Soap Based Webservice version 0.1
 * 
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "BioMartSoapService", targetNamespace = "http://www.biomart.org:80/MartServiceSoap", wsdlLocation = "file:/C:/Users/andrew.cassin/AppData/Local/Temp/tempdir2783990933872150234.tmp/martwsdl_1.wsdl")
public class BioMartSoapService
    extends Service
{

    private final static URL BIOMARTSOAPSERVICE_WSDL_LOCATION;
    private final static WebServiceException BIOMARTSOAPSERVICE_EXCEPTION;
    private final static QName BIOMARTSOAPSERVICE_QNAME = new QName("http://www.biomart.org:80/MartServiceSoap", "BioMartSoapService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/C:/Users/andrew.cassin/AppData/Local/Temp/tempdir2783990933872150234.tmp/martwsdl_1.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        BIOMARTSOAPSERVICE_WSDL_LOCATION = url;
        BIOMARTSOAPSERVICE_EXCEPTION = e;
    }

    public BioMartSoapService() {
        super(__getWsdlLocation(), BIOMARTSOAPSERVICE_QNAME);
    }

    public BioMartSoapService(WebServiceFeature... features) {
        super(__getWsdlLocation(), BIOMARTSOAPSERVICE_QNAME, features);
    }

    public BioMartSoapService(URL wsdlLocation) {
        super(wsdlLocation, BIOMARTSOAPSERVICE_QNAME);
    }

    public BioMartSoapService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, BIOMARTSOAPSERVICE_QNAME, features);
    }

    public BioMartSoapService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public BioMartSoapService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns MartServiceSoap
     */
    @WebEndpoint(name = "BioMartSoapPort")
    public MartServiceSoap getBioMartSoapPort() {
        return super.getPort(new QName("http://www.biomart.org:80/MartServiceSoap", "BioMartSoapPort"), MartServiceSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns MartServiceSoap
     */
    @WebEndpoint(name = "BioMartSoapPort")
    public MartServiceSoap getBioMartSoapPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.biomart.org:80/MartServiceSoap", "BioMartSoapPort"), MartServiceSoap.class, features);
    }

    private static URL __getWsdlLocation() {
        if (BIOMARTSOAPSERVICE_EXCEPTION!= null) {
            throw BIOMARTSOAPSERVICE_EXCEPTION;
        }
        return BIOMARTSOAPSERVICE_WSDL_LOCATION;
    }

}
