
package au.edu.unimelb.plantcell.io.ws.biomart.soap;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "BioMartException", targetNamespace = "http://www.biomart.org:80/MartServiceSoap")
public class BioMartException_Exception
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private BioMartException faultInfo;

    /**
     * 
     * @param message
     * @param faultInfo
     */
    public BioMartException_Exception(String message, BioMartException faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param message
     * @param faultInfo
     * @param cause
     */
    public BioMartException_Exception(String message, BioMartException faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: au.edu.unimelb.plantcell.io.ws.biomart.soap.BioMartException
     */
    public BioMartException getFaultInfo() {
        return faultInfo;
    }

}
