
package au.edu.unimelb.plantcell.io.ws.biomart.soap;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "MartServiceSoap", targetNamespace = "http://www.biomart.org:80/MartServiceSoap")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface MartServiceSoap {


    /**
     * 
     * @return
     *     returns java.util.List<au.edu.unimelb.plantcell.io.ws.biomart.soap.Mart>
     * @throws BioMartException_Exception
     */
    @WebMethod
    @WebResult(name = "mart", targetNamespace = "")
    @RequestWrapper(localName = "getRegistry", targetNamespace = "http://www.biomart.org:80/MartServiceSoap", className = "au.edu.unimelb.plantcell.io.ws.biomart.soap.GetRegistry")
    @ResponseWrapper(localName = "getRegistryResponse", targetNamespace = "http://www.biomart.org:80/MartServiceSoap", className = "au.edu.unimelb.plantcell.io.ws.biomart.soap.GetRegistryResponse")
    public List<Mart> getRegistry()
        throws BioMartException_Exception
    ;

    /**
     * 
     * @param martName
     * @return
     *     returns java.util.List<au.edu.unimelb.plantcell.io.ws.biomart.soap.DatasetInfo>
     * @throws BioMartException_Exception
     */
    @WebMethod
    @WebResult(name = "datasetInfo", targetNamespace = "")
    @RequestWrapper(localName = "getDatasets", targetNamespace = "http://www.biomart.org:80/MartServiceSoap", className = "au.edu.unimelb.plantcell.io.ws.biomart.soap.GetDatasets")
    @ResponseWrapper(localName = "getDatasetsResponse", targetNamespace = "http://www.biomart.org:80/MartServiceSoap", className = "au.edu.unimelb.plantcell.io.ws.biomart.soap.GetDatasetsResponse")
    public List<DatasetInfo> getDatasets(
        @WebParam(name = "martName", targetNamespace = "")
        String martName)
        throws BioMartException_Exception
    ;

    /**
     * 
     * @param datasetName
     * @param virtualSchema
     * @return
     *     returns java.util.List<au.edu.unimelb.plantcell.io.ws.biomart.soap.AttributePage>
     * @throws BioMartException_Exception
     */
    @WebMethod
    @WebResult(name = "attributePage", targetNamespace = "")
    @RequestWrapper(localName = "getAttributes", targetNamespace = "http://www.biomart.org:80/MartServiceSoap", className = "au.edu.unimelb.plantcell.io.ws.biomart.soap.GetAttributes")
    @ResponseWrapper(localName = "getAttributesResponse", targetNamespace = "http://www.biomart.org:80/MartServiceSoap", className = "au.edu.unimelb.plantcell.io.ws.biomart.soap.GetAttributesResponse")
    public List<AttributePage> getAttributes(
        @WebParam(name = "datasetName", targetNamespace = "")
        String datasetName,
        @WebParam(name = "virtualSchema", targetNamespace = "")
        String virtualSchema)
        throws BioMartException_Exception
    ;

    /**
     * 
     * @param datasetName
     * @param virtualSchema
     * @return
     *     returns java.util.List<au.edu.unimelb.plantcell.io.ws.biomart.soap.FilterPage>
     * @throws BioMartException_Exception
     */
    @WebMethod
    @WebResult(name = "filterPage", targetNamespace = "")
    @RequestWrapper(localName = "getFilters", targetNamespace = "http://www.biomart.org:80/MartServiceSoap", className = "au.edu.unimelb.plantcell.io.ws.biomart.soap.GetFilters")
    @ResponseWrapper(localName = "getFiltersResponse", targetNamespace = "http://www.biomart.org:80/MartServiceSoap", className = "au.edu.unimelb.plantcell.io.ws.biomart.soap.GetFiltersResponse")
    public List<FilterPage> getFilters(
        @WebParam(name = "datasetName", targetNamespace = "")
        String datasetName,
        @WebParam(name = "virtualSchema", targetNamespace = "")
        String virtualSchema)
        throws BioMartException_Exception
    ;

    /**
     * 
     * @param virtualSchemaName
     * @param count
     * @param dataset
     * @param header
     * @param uniqueRows
     * @return
     *     returns java.util.List<au.edu.unimelb.plantcell.io.ws.biomart.soap.ResultsRow>
     * @throws BioMartException_Exception
     */
    @WebMethod
    @WebResult(name = "resultsRow", targetNamespace = "")
    @RequestWrapper(localName = "query", targetNamespace = "http://www.biomart.org:80/MartServiceSoap", className = "au.edu.unimelb.plantcell.io.ws.biomart.soap.Query")
    @ResponseWrapper(localName = "queryResponse", targetNamespace = "http://www.biomart.org:80/MartServiceSoap", className = "au.edu.unimelb.plantcell.io.ws.biomart.soap.QueryResponse")
    public List<ResultsRow> query(
        @WebParam(name = "virtualSchemaName", targetNamespace = "")
        String virtualSchemaName,
        @WebParam(name = "header", targetNamespace = "")
        int header,
        @WebParam(name = "count", targetNamespace = "")
        int count,
        @WebParam(name = "uniqueRows", targetNamespace = "")
        int uniqueRows,
        @WebParam(name = "Dataset", targetNamespace = "")
        List<Dataset> dataset)
        throws BioMartException_Exception
    ;

}
