//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.05.30 at 08:19:45 AM EST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.plantcell.unimelb.edu.au/bioinformatics/ns/MascotEE/v2", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package au.edu.unimelb.plantcell.servers.mascotee.jaxb;
