//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-558 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.06.27 at 10:11:06 AM EST 
//


package au.edu.unimelb.plantcell.servers.msconvertee.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for AbsoluteThresholdType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="AbsoluteThresholdType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="what">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.plantcell.unimelb.edu.au/bioinformatics/schemas/v1/msconvertee}MostOrLeast">
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="intensity_threshold" type="{http://www.w3.org/2001/XMLSchema}double" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AbsoluteThresholdType")
public class AbsoluteThresholdType {

    @XmlAttribute
    protected MostOrLeast what;
    @XmlAttribute(name = "intensity_threshold")
    protected Double intensityThreshold;

    /**
     * Gets the value of the what property.
     * 
     * @return
     *     possible object is
     *     {@link MostOrLeast }
     *     
     */
    public MostOrLeast getWhat() {
        return what;
    }

    /**
     * Sets the value of the what property.
     * 
     * @param value
     *     allowed object is
     *     {@link MostOrLeast }
     *     
     */
    public void setWhat(MostOrLeast value) {
        this.what = value;
    }

    /**
     * Gets the value of the intensityThreshold property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getIntensityThreshold() {
        return intensityThreshold;
    }

    /**
     * Sets the value of the intensityThreshold property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setIntensityThreshold(Double value) {
        this.intensityThreshold = value;
    }

}
