//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-558 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.06.27 at 10:11:06 AM EST 
//


package au.edu.unimelb.plantcell.servers.msconvertee.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for MS2DeisotopeType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="MS2DeisotopeType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="hires" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="mz_tolerance" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "MS2DeisotopeType", propOrder = {
    "hires",
    "mzTolerance"
})
public class MS2DeisotopeType {

    protected boolean hires;
    @XmlElement(name = "mz_tolerance")
    protected Double mzTolerance;

    /**
     * Gets the value of the hires property.
     * 
     */
    public boolean isHires() {
        return hires;
    }

    /**
     * Sets the value of the hires property.
     * 
     */
    public void setHires(boolean value) {
        this.hires = value;
    }

    /**
     * Gets the value of the mzTolerance property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getMzTolerance() {
        return mzTolerance;
    }

    /**
     * Sets the value of the mzTolerance property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setMzTolerance(Double value) {
        this.mzTolerance = value;
    }

}
