//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-558 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.06.27 at 10:11:06 AM EST 
//


package au.edu.unimelb.plantcell.servers.msconvertee.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Selects the specified scans to include in the output 
 * (typically an integer is expected, although we permit non-integer values to support wierd formats)
 * 
 * 
 * <p>Java class for scanFilterType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="scanFilterType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="firstInclusive" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="lastInclusive" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "scanFilterType", propOrder = {
    "firstInclusive",
    "lastInclusive"
})
public class ScanFilterType {

    @XmlElement(required = true)
    protected String firstInclusive;
    @XmlElement(required = true)
    protected String lastInclusive;

    /**
     * Gets the value of the firstInclusive property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFirstInclusive() {
        return firstInclusive;
    }

    /**
     * Sets the value of the firstInclusive property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFirstInclusive(String value) {
        this.firstInclusive = value;
    }

    /**
     * Gets the value of the lastInclusive property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLastInclusive() {
        return lastInclusive;
    }

    /**
     * Sets the value of the lastInclusive property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLastInclusive(String value) {
        this.lastInclusive = value;
    }

}
