//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-558 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.07.07 at 08:09:58 AM EST 
//


package au.edu.unimelb.plantcell.servers.msconvertee.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ScanFilterType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ScanFilterType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;element name="numberFilter" type="{http://www.plantcell.unimelb.edu.au/bioinformatics/schemas/v1/msconvertee}ScanNumberFilterType"/>
 *         &lt;element name="eventFilter" type="{http://www.plantcell.unimelb.edu.au/bioinformatics/schemas/v1/msconvertee}ScanEventFilterType"/>
 *         &lt;element name="timeFilter" type="{http://www.plantcell.unimelb.edu.au/bioinformatics/schemas/v1/msconvertee}ScanTimeFilterType"/>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ScanFilterType", propOrder = {
    "numberFilter",
    "eventFilter",
    "timeFilter"
})
public class ScanFilterType {

    protected ScanNumberFilterType numberFilter;
    protected ScanEventFilterType eventFilter;
    protected ScanTimeFilterType timeFilter;

    /**
     * Gets the value of the numberFilter property.
     * 
     * @return
     *     possible object is
     *     {@link ScanNumberFilterType }
     *     
     */
    public ScanNumberFilterType getNumberFilter() {
        return numberFilter;
    }

    /**
     * Sets the value of the numberFilter property.
     * 
     * @param value
     *     allowed object is
     *     {@link ScanNumberFilterType }
     *     
     */
    public void setNumberFilter(ScanNumberFilterType value) {
        this.numberFilter = value;
    }

    /**
     * Gets the value of the eventFilter property.
     * 
     * @return
     *     possible object is
     *     {@link ScanEventFilterType }
     *     
     */
    public ScanEventFilterType getEventFilter() {
        return eventFilter;
    }

    /**
     * Sets the value of the eventFilter property.
     * 
     * @param value
     *     allowed object is
     *     {@link ScanEventFilterType }
     *     
     */
    public void setEventFilter(ScanEventFilterType value) {
        this.eventFilter = value;
    }

    /**
     * Gets the value of the timeFilter property.
     * 
     * @return
     *     possible object is
     *     {@link ScanTimeFilterType }
     *     
     */
    public ScanTimeFilterType getTimeFilter() {
        return timeFilter;
    }

    /**
     * Sets the value of the timeFilter property.
     * 
     * @param value
     *     allowed object is
     *     {@link ScanTimeFilterType }
     *     
     */
    public void setTimeFilter(ScanTimeFilterType value) {
        this.timeFilter = value;
    }

}
