//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-558 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.07.07 at 08:09:58 AM EST 
//


package au.edu.unimelb.plantcell.servers.msconvertee.jaxb;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ProteowizardJobType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ProteowizardJobType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="OutputFormat">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;enumeration value="MGF"/>
 *               &lt;enumeration value="MzML"/>
 *               &lt;enumeration value="MzXML"/>
 *               &lt;minLength value="3"/>
 *               &lt;maxLength value="20"/>
 *               &lt;enumeration value="MZ5"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="FilterParameters" type="{http://www.plantcell.unimelb.edu.au/bioinformatics/schemas/v1/msconvertee}FilterParametersType" minOccurs="0"/>
 *         &lt;element name="Compression" type="{http://www.plantcell.unimelb.edu.au/bioinformatics/schemas/v1/msconvertee}CompressionType" minOccurs="0"/>
 *         &lt;element name="PrecursorCorrection" type="{http://www.plantcell.unimelb.edu.au/bioinformatics/schemas/v1/msconvertee}PrecursorCorrectionType" minOccurs="0"/>
 *         &lt;element name="inputDataFormat">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;enumeration value="wiff"/>
 *               &lt;enumeration value="raw"/>
 *               &lt;enumeration value="mgf"/>
 *               &lt;enumeration value="mzml"/>
 *               &lt;enumeration value="mzxml"/>
 *               &lt;enumeration value="mz5"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="inputDataNames" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ProteowizardJobType", propOrder = {
    "outputFormat",
    "filterParameters",
    "compression",
    "precursorCorrection",
    "inputDataFormat",
    "inputDataNames"
})
public class ProteowizardJobType {

    @XmlElement(name = "OutputFormat", required = true, defaultValue = "MzML")
    protected String outputFormat;
    @XmlElement(name = "FilterParameters")
    protected FilterParametersType filterParameters;
    @XmlElement(name = "Compression")
    protected CompressionType compression;
    @XmlElement(name = "PrecursorCorrection")
    protected PrecursorCorrectionType precursorCorrection;
    @XmlElement(required = true)
    protected String inputDataFormat;
    @XmlElement(required = true)
    protected List<String> inputDataNames;

    /**
     * Gets the value of the outputFormat property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOutputFormat() {
        return outputFormat;
    }

    /**
     * Sets the value of the outputFormat property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOutputFormat(String value) {
        this.outputFormat = value;
    }

    /**
     * Gets the value of the filterParameters property.
     * 
     * @return
     *     possible object is
     *     {@link FilterParametersType }
     *     
     */
    public FilterParametersType getFilterParameters() {
        return filterParameters;
    }

    /**
     * Sets the value of the filterParameters property.
     * 
     * @param value
     *     allowed object is
     *     {@link FilterParametersType }
     *     
     */
    public void setFilterParameters(FilterParametersType value) {
        this.filterParameters = value;
    }

    /**
     * Gets the value of the compression property.
     * 
     * @return
     *     possible object is
     *     {@link CompressionType }
     *     
     */
    public CompressionType getCompression() {
        return compression;
    }

    /**
     * Sets the value of the compression property.
     * 
     * @param value
     *     allowed object is
     *     {@link CompressionType }
     *     
     */
    public void setCompression(CompressionType value) {
        this.compression = value;
    }

    /**
     * Gets the value of the precursorCorrection property.
     * 
     * @return
     *     possible object is
     *     {@link PrecursorCorrectionType }
     *     
     */
    public PrecursorCorrectionType getPrecursorCorrection() {
        return precursorCorrection;
    }

    /**
     * Sets the value of the precursorCorrection property.
     * 
     * @param value
     *     allowed object is
     *     {@link PrecursorCorrectionType }
     *     
     */
    public void setPrecursorCorrection(PrecursorCorrectionType value) {
        this.precursorCorrection = value;
    }

    /**
     * Gets the value of the inputDataFormat property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInputDataFormat() {
        return inputDataFormat;
    }

    /**
     * Sets the value of the inputDataFormat property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInputDataFormat(String value) {
        this.inputDataFormat = value;
    }

    /**
     * Gets the value of the inputDataNames property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the inputDataNames property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getInputDataNames().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getInputDataNames() {
        if (inputDataNames == null) {
            inputDataNames = new ArrayList<String>();
        }
        return this.inputDataNames;
    }

}
