//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-558 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.06.27 at 10:11:06 AM EST 
//


package au.edu.unimelb.plantcell.servers.msconvertee.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ThresholdParametersType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ThresholdParametersType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;sequence>
 *           &lt;choice>
 *             &lt;element name="TICAbsoluteThreshold" type="{http://www.plantcell.unimelb.edu.au/bioinformatics/schemas/v1/msconvertee}AbsoluteThresholdType"/>
 *             &lt;element name="TICRelativeThreshold" type="{http://www.plantcell.unimelb.edu.au/bioinformatics/schemas/v1/msconvertee}RelativeThresholdType"/>
 *             &lt;element name="BasePeakRelativeThreshold" type="{http://www.plantcell.unimelb.edu.au/bioinformatics/schemas/v1/msconvertee}RelativeThresholdType"/>
 *             &lt;element name="AbsoluteThreshold" type="{http://www.plantcell.unimelb.edu.au/bioinformatics/schemas/v1/msconvertee}AbsoluteThresholdType"/>
 *             &lt;element name="KeepNThresholdIncludingTies" type="{http://www.plantcell.unimelb.edu.au/bioinformatics/schemas/v1/msconvertee}KeepNThresholdType"/>
 *             &lt;element name="KeepNThreshold" type="{http://www.plantcell.unimelb.edu.au/bioinformatics/schemas/v1/msconvertee}KeepNThresholdType"/>
 *           &lt;/choice>
 *         &lt;/sequence>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ThresholdParametersType", propOrder = {
    "ticAbsoluteThreshold",
    "ticRelativeThreshold",
    "basePeakRelativeThreshold",
    "absoluteThreshold",
    "keepNThresholdIncludingTies",
    "keepNThreshold"
})
public class ThresholdParametersType {

    @XmlElement(name = "TICAbsoluteThreshold")
    protected AbsoluteThresholdType ticAbsoluteThreshold;
    @XmlElement(name = "TICRelativeThreshold")
    protected RelativeThresholdType ticRelativeThreshold;
    @XmlElement(name = "BasePeakRelativeThreshold")
    protected RelativeThresholdType basePeakRelativeThreshold;
    @XmlElement(name = "AbsoluteThreshold")
    protected AbsoluteThresholdType absoluteThreshold;
    @XmlElement(name = "KeepNThresholdIncludingTies")
    protected KeepNThresholdType keepNThresholdIncludingTies;
    @XmlElement(name = "KeepNThreshold")
    protected KeepNThresholdType keepNThreshold;

    /**
     * Gets the value of the ticAbsoluteThreshold property.
     * 
     * @return
     *     possible object is
     *     {@link AbsoluteThresholdType }
     *     
     */
    public AbsoluteThresholdType getTICAbsoluteThreshold() {
        return ticAbsoluteThreshold;
    }

    /**
     * Sets the value of the ticAbsoluteThreshold property.
     * 
     * @param value
     *     allowed object is
     *     {@link AbsoluteThresholdType }
     *     
     */
    public void setTICAbsoluteThreshold(AbsoluteThresholdType value) {
        this.ticAbsoluteThreshold = value;
    }

    /**
     * Gets the value of the ticRelativeThreshold property.
     * 
     * @return
     *     possible object is
     *     {@link RelativeThresholdType }
     *     
     */
    public RelativeThresholdType getTICRelativeThreshold() {
        return ticRelativeThreshold;
    }

    /**
     * Sets the value of the ticRelativeThreshold property.
     * 
     * @param value
     *     allowed object is
     *     {@link RelativeThresholdType }
     *     
     */
    public void setTICRelativeThreshold(RelativeThresholdType value) {
        this.ticRelativeThreshold = value;
    }

    /**
     * Gets the value of the basePeakRelativeThreshold property.
     * 
     * @return
     *     possible object is
     *     {@link RelativeThresholdType }
     *     
     */
    public RelativeThresholdType getBasePeakRelativeThreshold() {
        return basePeakRelativeThreshold;
    }

    /**
     * Sets the value of the basePeakRelativeThreshold property.
     * 
     * @param value
     *     allowed object is
     *     {@link RelativeThresholdType }
     *     
     */
    public void setBasePeakRelativeThreshold(RelativeThresholdType value) {
        this.basePeakRelativeThreshold = value;
    }

    /**
     * Gets the value of the absoluteThreshold property.
     * 
     * @return
     *     possible object is
     *     {@link AbsoluteThresholdType }
     *     
     */
    public AbsoluteThresholdType getAbsoluteThreshold() {
        return absoluteThreshold;
    }

    /**
     * Sets the value of the absoluteThreshold property.
     * 
     * @param value
     *     allowed object is
     *     {@link AbsoluteThresholdType }
     *     
     */
    public void setAbsoluteThreshold(AbsoluteThresholdType value) {
        this.absoluteThreshold = value;
    }

    /**
     * Gets the value of the keepNThresholdIncludingTies property.
     * 
     * @return
     *     possible object is
     *     {@link KeepNThresholdType }
     *     
     */
    public KeepNThresholdType getKeepNThresholdIncludingTies() {
        return keepNThresholdIncludingTies;
    }

    /**
     * Sets the value of the keepNThresholdIncludingTies property.
     * 
     * @param value
     *     allowed object is
     *     {@link KeepNThresholdType }
     *     
     */
    public void setKeepNThresholdIncludingTies(KeepNThresholdType value) {
        this.keepNThresholdIncludingTies = value;
    }

    /**
     * Gets the value of the keepNThreshold property.
     * 
     * @return
     *     possible object is
     *     {@link KeepNThresholdType }
     *     
     */
    public KeepNThresholdType getKeepNThreshold() {
        return keepNThreshold;
    }

    /**
     * Sets the value of the keepNThreshold property.
     * 
     * @param value
     *     allowed object is
     *     {@link KeepNThresholdType }
     *     
     */
    public void setKeepNThreshold(KeepNThresholdType value) {
        this.keepNThreshold = value;
    }

}
