
package au.edu.unimelb.plantcell.servers.tmhmm;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "TMHMMServicePortType", targetNamespace = "http://nectar.plantcell.unimelb.edu.au")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface TMHMMServicePortType {


    /**
     * 
     * @param fastaSequences
     * @param organism
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "urn:submit")
    @WebResult(targetNamespace = "http://nectar.plantcell.unimelb.edu.au")
    @RequestWrapper(localName = "submit", targetNamespace = "http://nectar.plantcell.unimelb.edu.au", className = "au.edu.unimelb.plantcell.servers.tmhmm.Submit")
    @ResponseWrapper(localName = "submitResponse", targetNamespace = "http://nectar.plantcell.unimelb.edu.au", className = "au.edu.unimelb.plantcell.servers.tmhmm.SubmitResponse")
    public String submit(
        @WebParam(name = "fasta_sequences", targetNamespace = "http://nectar.plantcell.unimelb.edu.au")
        String fastaSequences,
        @WebParam(name = "organism", targetNamespace = "http://nectar.plantcell.unimelb.edu.au")
        String organism);

    /**
     * 
     * @param jobID
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "urn:getStatus")
    @WebResult(targetNamespace = "http://nectar.plantcell.unimelb.edu.au")
    @RequestWrapper(localName = "getStatus", targetNamespace = "http://nectar.plantcell.unimelb.edu.au", className = "au.edu.unimelb.plantcell.servers.tmhmm.GetStatus")
    @ResponseWrapper(localName = "getStatusResponse", targetNamespace = "http://nectar.plantcell.unimelb.edu.au", className = "au.edu.unimelb.plantcell.servers.tmhmm.GetStatusResponse")
    public String getStatus(
        @WebParam(name = "jobID", targetNamespace = "http://nectar.plantcell.unimelb.edu.au")
        String jobID);

    /**
     * 
     * @param jobID
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "urn:getResult")
    @WebResult(targetNamespace = "http://nectar.plantcell.unimelb.edu.au")
    @RequestWrapper(localName = "getResult", targetNamespace = "http://nectar.plantcell.unimelb.edu.au", className = "au.edu.unimelb.plantcell.servers.tmhmm.GetResult")
    @ResponseWrapper(localName = "getResultResponse", targetNamespace = "http://nectar.plantcell.unimelb.edu.au", className = "au.edu.unimelb.plantcell.servers.tmhmm.GetResultResponse")
    public String getResult(
        @WebParam(name = "jobID", targetNamespace = "http://nectar.plantcell.unimelb.edu.au")
        String jobID);

}
