
package au.edu.unimelb.plantcell.servers.tmhmm;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "TMHMMService", targetNamespace = "http://nectar.plantcell.unimelb.edu.au", wsdlLocation = "file:/C:/Users/andrew.cassin/AppData/Local/Temp/tempdir5240118897770237127.tmp/tmhmm_service_1.wsdl")
public class TMHMMService
    extends Service
{

    private final static URL TMHMMSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(au.edu.unimelb.plantcell.servers.tmhmm.TMHMMService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = au.edu.unimelb.plantcell.servers.tmhmm.TMHMMService.class.getResource(".");
            url = new URL(baseUrl, "file:/C:/Users/andrew.cassin/AppData/Local/Temp/tempdir5240118897770237127.tmp/tmhmm_service_1.wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'file:/C:/Users/andrew.cassin/AppData/Local/Temp/tempdir5240118897770237127.tmp/tmhmm_service_1.wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        TMHMMSERVICE_WSDL_LOCATION = url;
    }

    public TMHMMService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public TMHMMService() {
        super(TMHMMSERVICE_WSDL_LOCATION, new QName("http://nectar.plantcell.unimelb.edu.au", "TMHMMService"));
    }

    /**
     * 
     * @return
     *     returns TMHMMServicePortType
     */
    @WebEndpoint(name = "TMHMMServiceHttpSoap11Endpoint")
    public TMHMMServicePortType getTMHMMServiceHttpSoap11Endpoint() {
        return super.getPort(new QName("http://nectar.plantcell.unimelb.edu.au", "TMHMMServiceHttpSoap11Endpoint"), TMHMMServicePortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns TMHMMServicePortType
     */
    @WebEndpoint(name = "TMHMMServiceHttpSoap11Endpoint")
    public TMHMMServicePortType getTMHMMServiceHttpSoap11Endpoint(WebServiceFeature... features) {
        return super.getPort(new QName("http://nectar.plantcell.unimelb.edu.au", "TMHMMServiceHttpSoap11Endpoint"), TMHMMServicePortType.class, features);
    }

}
