
package au.edu.unimelb.plantcell.servers.nectar.targetp;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "TargetPServicePortType", targetNamespace = "http://nectar.plantcell.unimelb.edu.au")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface TargetPServicePortType {


    /**
     * 
     * @param fasta
     * @param spCutoff
     * @param cpCutoff
     * @param mCutoff
     * @param oCutoff
     * @param isPlant
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "urn:submit")
    @WebResult(targetNamespace = "http://nectar.plantcell.unimelb.edu.au")
    @RequestWrapper(localName = "submit", targetNamespace = "http://nectar.plantcell.unimelb.edu.au", className = "au.edu.unimelb.plantcell.servers.nectar.targetp.Submit")
    @ResponseWrapper(localName = "submitResponse", targetNamespace = "http://nectar.plantcell.unimelb.edu.au", className = "au.edu.unimelb.plantcell.servers.nectar.targetp.SubmitResponse")
    public String submit(
        @WebParam(name = "is_plant", targetNamespace = "http://nectar.plantcell.unimelb.edu.au")
        Boolean isPlant,
        @WebParam(name = "cp_cutoff", targetNamespace = "http://nectar.plantcell.unimelb.edu.au")
        Double cpCutoff,
        @WebParam(name = "sp_cutoff", targetNamespace = "http://nectar.plantcell.unimelb.edu.au")
        Double spCutoff,
        @WebParam(name = "m_cutoff", targetNamespace = "http://nectar.plantcell.unimelb.edu.au")
        Double mCutoff,
        @WebParam(name = "o_cutoff", targetNamespace = "http://nectar.plantcell.unimelb.edu.au")
        Double oCutoff,
        @WebParam(name = "fasta", targetNamespace = "http://nectar.plantcell.unimelb.edu.au")
        String fasta);

    /**
     * 
     * @param jobId
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "urn:getStatus")
    @WebResult(targetNamespace = "http://nectar.plantcell.unimelb.edu.au")
    @RequestWrapper(localName = "getStatus", targetNamespace = "http://nectar.plantcell.unimelb.edu.au", className = "au.edu.unimelb.plantcell.servers.nectar.targetp.GetStatus")
    @ResponseWrapper(localName = "getStatusResponse", targetNamespace = "http://nectar.plantcell.unimelb.edu.au", className = "au.edu.unimelb.plantcell.servers.nectar.targetp.GetStatusResponse")
    public String getStatus(
        @WebParam(name = "job_id", targetNamespace = "http://nectar.plantcell.unimelb.edu.au")
        String jobId);

    /**
     * 
     * @param jobId
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "urn:getResult")
    @WebResult(targetNamespace = "http://nectar.plantcell.unimelb.edu.au")
    @RequestWrapper(localName = "getResult", targetNamespace = "http://nectar.plantcell.unimelb.edu.au", className = "au.edu.unimelb.plantcell.servers.nectar.targetp.GetResult")
    @ResponseWrapper(localName = "getResultResponse", targetNamespace = "http://nectar.plantcell.unimelb.edu.au", className = "au.edu.unimelb.plantcell.servers.nectar.targetp.GetResultResponse")
    public String getResult(
        @WebParam(name = "job_id", targetNamespace = "http://nectar.plantcell.unimelb.edu.au")
        String jobId);

}
