
package au.edu.unimelb.plantcell.servers.nectar.signalp;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "SignalPService", targetNamespace = "http://nectar.plantcell.unimelb.edu.au", wsdlLocation = "file:/C:/cygwin/home/andrew.cassin/test.outoftheway/signalp@nectar/SignalPService.wsdl")
public class SignalPService
    extends Service
{

    private final static URL SIGNALPSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(au.edu.unimelb.plantcell.servers.nectar.signalp.SignalPService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = au.edu.unimelb.plantcell.servers.nectar.signalp.SignalPService.class.getResource(".");
            url = new URL(baseUrl, "file:/C:/cygwin/home/andrew.cassin/test.outoftheway/signalp@nectar/SignalPService.wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'file:/C:/cygwin/home/andrew.cassin/test.outoftheway/signalp@nectar/SignalPService.wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        SIGNALPSERVICE_WSDL_LOCATION = url;
    }

    public SignalPService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SignalPService() {
        super(SIGNALPSERVICE_WSDL_LOCATION, new QName("http://nectar.plantcell.unimelb.edu.au", "SignalPService"));
    }

    /**
     * 
     * @return
     *     returns SignalPServicePortType
     */
    @WebEndpoint(name = "SignalPServiceHttpSoap11Endpoint")
    public SignalPServicePortType getSignalPServiceHttpSoap11Endpoint() {
        return super.getPort(new QName("http://nectar.plantcell.unimelb.edu.au", "SignalPServiceHttpSoap11Endpoint"), SignalPServicePortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SignalPServicePortType
     */
    @WebEndpoint(name = "SignalPServiceHttpSoap11Endpoint")
    public SignalPServicePortType getSignalPServiceHttpSoap11Endpoint(WebServiceFeature... features) {
        return super.getPort(new QName("http://nectar.plantcell.unimelb.edu.au", "SignalPServiceHttpSoap11Endpoint"), SignalPServicePortType.class, features);
    }

}
