
package au.edu.unimelb.plantcell.servers.nectar.signalp;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "SignalPServicePortType", targetNamespace = "http://nectar.plantcell.unimelb.edu.au")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface SignalPServicePortType {


    /**
     * 
     * @param fasta
     * @param notmCutoff
     * @param length
     * @param eukPlusNeg
     * @param tmCutoff
     * @param bestOrNotm
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "urn:submit")
    @WebResult(targetNamespace = "http://nectar.plantcell.unimelb.edu.au")
    @RequestWrapper(localName = "submit", targetNamespace = "http://nectar.plantcell.unimelb.edu.au", className = "au.edu.unimelb.plantcell.servers.nectar.signalp.Submit")
    @ResponseWrapper(localName = "submitResponse", targetNamespace = "http://nectar.plantcell.unimelb.edu.au", className = "au.edu.unimelb.plantcell.servers.nectar.signalp.SubmitResponse")
    public String submit(
        @WebParam(name = "fasta", targetNamespace = "http://nectar.plantcell.unimelb.edu.au")
        String fasta,
        @WebParam(name = "tm_cutoff", targetNamespace = "http://nectar.plantcell.unimelb.edu.au")
        Double tmCutoff,
        @WebParam(name = "notm_cutoff", targetNamespace = "http://nectar.plantcell.unimelb.edu.au")
        Double notmCutoff,
        @WebParam(name = "best_or_notm", targetNamespace = "http://nectar.plantcell.unimelb.edu.au")
        Boolean bestOrNotm,
        @WebParam(name = "length", targetNamespace = "http://nectar.plantcell.unimelb.edu.au")
        Integer length,
        @WebParam(name = "euk_plus_neg", targetNamespace = "http://nectar.plantcell.unimelb.edu.au")
        String eukPlusNeg);

    /**
     * 
     * @param jobId
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "urn:getStatus")
    @WebResult(targetNamespace = "http://nectar.plantcell.unimelb.edu.au")
    @RequestWrapper(localName = "getStatus", targetNamespace = "http://nectar.plantcell.unimelb.edu.au", className = "au.edu.unimelb.plantcell.servers.nectar.signalp.GetStatus")
    @ResponseWrapper(localName = "getStatusResponse", targetNamespace = "http://nectar.plantcell.unimelb.edu.au", className = "au.edu.unimelb.plantcell.servers.nectar.signalp.GetStatusResponse")
    public String getStatus(
        @WebParam(name = "job_id", targetNamespace = "http://nectar.plantcell.unimelb.edu.au")
        String jobId);

    /**
     * 
     * @param jobId
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "urn:getResult")
    @WebResult(targetNamespace = "http://nectar.plantcell.unimelb.edu.au")
    @RequestWrapper(localName = "getResult", targetNamespace = "http://nectar.plantcell.unimelb.edu.au", className = "au.edu.unimelb.plantcell.servers.nectar.signalp.GetResult")
    @ResponseWrapper(localName = "getResultResponse", targetNamespace = "http://nectar.plantcell.unimelb.edu.au", className = "au.edu.unimelb.plantcell.servers.nectar.signalp.GetResultResponse")
    public String getResult(
        @WebParam(name = "job_id", targetNamespace = "http://nectar.plantcell.unimelb.edu.au")
        String jobId);

}
