
package au.edu.unimelb.plantcell.servers.bigpi;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "BIGPIService", targetNamespace = "http://nectar.plantcell.unimelb.edu.au", wsdlLocation = "file:/C:/Users/andrew.cassin/AppData/Local/Temp/tempdir6414970617896175331.tmp/BIGPIService_1.wsdl")
public class BIGPIService
    extends Service
{

    private final static URL BIGPISERVICE_WSDL_LOCATION;
    private final static WebServiceException BIGPISERVICE_EXCEPTION;
    private final static QName BIGPISERVICE_QNAME = new QName("http://nectar.plantcell.unimelb.edu.au", "BIGPIService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/C:/Users/andrew.cassin/AppData/Local/Temp/tempdir6414970617896175331.tmp/BIGPIService_1.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        BIGPISERVICE_WSDL_LOCATION = url;
        BIGPISERVICE_EXCEPTION = e;
    }

    public BIGPIService() {
        super(__getWsdlLocation(), BIGPISERVICE_QNAME);
    }

    public BIGPIService(WebServiceFeature... features) {
        super(__getWsdlLocation(), BIGPISERVICE_QNAME, features);
    }

    public BIGPIService(URL wsdlLocation) {
        super(wsdlLocation, BIGPISERVICE_QNAME);
    }

    public BIGPIService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, BIGPISERVICE_QNAME, features);
    }

    public BIGPIService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public BIGPIService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns BIGPIServicePortType
     */
    @WebEndpoint(name = "BIGPIServiceHttpSoap11Endpoint")
    public BIGPIServicePortType getBIGPIServiceHttpSoap11Endpoint() {
        return super.getPort(new QName("http://nectar.plantcell.unimelb.edu.au", "BIGPIServiceHttpSoap11Endpoint"), BIGPIServicePortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns BIGPIServicePortType
     */
    @WebEndpoint(name = "BIGPIServiceHttpSoap11Endpoint")
    public BIGPIServicePortType getBIGPIServiceHttpSoap11Endpoint(WebServiceFeature... features) {
        return super.getPort(new QName("http://nectar.plantcell.unimelb.edu.au", "BIGPIServiceHttpSoap11Endpoint"), BIGPIServicePortType.class, features);
    }

    private static URL __getWsdlLocation() {
        if (BIGPISERVICE_EXCEPTION!= null) {
            throw BIGPISERVICE_EXCEPTION;
        }
        return BIGPISERVICE_WSDL_LOCATION;
    }

}
