//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.03.06 at 01:00:16 PM EST 
//


package uk.ac.ebi.interpro.resources.schemas.interproscan5;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for FingerPrintsLocationType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="FingerPrintsLocationType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.ebi.ac.uk/interpro/resources/schemas/interproscan5}LocationType">
 *       &lt;sequence>
 *       &lt;/sequence>
 *       &lt;attribute name="motifNumber" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="pvalue" use="required" type="{http://www.w3.org/2001/XMLSchema}double" />
 *       &lt;attribute name="score" use="required" type="{http://www.w3.org/2001/XMLSchema}double" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "FingerPrintsLocationType")
public class FingerPrintsLocationType
    extends LocationType
{

    @XmlAttribute(name = "motifNumber", required = true)
    protected int motifNumber;
    @XmlAttribute(name = "pvalue", required = true)
    protected double pvalue;
    @XmlAttribute(name = "score", required = true)
    protected double score;

    /**
     * Gets the value of the motifNumber property.
     * 
     */
    public int getMotifNumber() {
        return motifNumber;
    }

    /**
     * Sets the value of the motifNumber property.
     * 
     */
    public void setMotifNumber(int value) {
        this.motifNumber = value;
    }

    /**
     * Gets the value of the pvalue property.
     * 
     */
    public double getPvalue() {
        return pvalue;
    }

    /**
     * Sets the value of the pvalue property.
     * 
     */
    public void setPvalue(double value) {
        this.pvalue = value;
    }

    /**
     * Gets the value of the score property.
     * 
     */
    public double getScore() {
        return score;
    }

    /**
     * Sets the value of the score property.
     * 
     */
    public void setScore(double value) {
        this.score = value;
    }

}
