//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.03.06 at 01:00:16 PM EST 
//


package uk.ac.ebi.interpro.resources.schemas.interproscan5;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for GoXrefType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="GoXrefType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.ebi.ac.uk/interpro/resources/schemas/interproscan5}XrefType">
 *       &lt;sequence>
 *       &lt;/sequence>
 *       &lt;attribute name="category" type="{http://www.ebi.ac.uk/interpro/resources/schemas/interproscan5}GoCategoryType" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "GoXrefType")
public class GoXrefType
    extends XrefType
{

    @XmlAttribute(name = "category")
    protected GoCategoryType category;

    /**
     * Gets the value of the category property.
     * 
     * @return
     *     possible object is
     *     {@link GoCategoryType }
     *     
     */
    public GoCategoryType getCategory() {
        return category;
    }

    /**
     * Sets the value of the category property.
     * 
     * @param value
     *     allowed object is
     *     {@link GoCategoryType }
     *     
     */
    public void setCategory(GoCategoryType value) {
        this.category = value;
    }

}
