//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.03.06 at 01:00:16 PM EST 
//


package uk.ac.ebi.interpro.resources.schemas.interproscan5;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Hmmer3LocationType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Hmmer3LocationType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.ebi.ac.uk/interpro/resources/schemas/interproscan5}HmmerLocationType">
 *       &lt;sequence>
 *       &lt;/sequence>
 *       &lt;attribute name="env-end" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="env-start" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Hmmer3LocationType")
public class Hmmer3LocationType
    extends HmmerLocationType
{

    @XmlAttribute(name = "env-end", required = true)
    protected int envEnd;
    @XmlAttribute(name = "env-start", required = true)
    protected int envStart;

    /**
     * Gets the value of the envEnd property.
     * 
     */
    public int getEnvEnd() {
        return envEnd;
    }

    /**
     * Sets the value of the envEnd property.
     * 
     */
    public void setEnvEnd(int value) {
        this.envEnd = value;
    }

    /**
     * Gets the value of the envStart property.
     * 
     */
    public int getEnvStart() {
        return envStart;
    }

    /**
     * Sets the value of the envStart property.
     * 
     */
    public void setEnvStart(int value) {
        this.envStart = value;
    }

}
