//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.03.06 at 01:00:16 PM EST 
//


package uk.ac.ebi.interpro.resources.schemas.interproscan5;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for locationsType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="locationsType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="blastprodom-location" type="{http://www.ebi.ac.uk/interpro/resources/schemas/interproscan5}BlastProDomLocationType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="coils-location" type="{http://www.ebi.ac.uk/interpro/resources/schemas/interproscan5}CoilsLocationType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="fingerprints-location" type="{http://www.ebi.ac.uk/interpro/resources/schemas/interproscan5}FingerPrintsLocationType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="hmmer2-location" type="{http://www.ebi.ac.uk/interpro/resources/schemas/interproscan5}Hmmer2LocationType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="hmmer3-location" type="{http://www.ebi.ac.uk/interpro/resources/schemas/interproscan5}Hmmer3LocationType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="panther-location" type="{http://www.ebi.ac.uk/interpro/resources/schemas/interproscan5}PantherLocationType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="patternscan-location" type="{http://www.ebi.ac.uk/interpro/resources/schemas/interproscan5}PatternScanLocationType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="phobius-location" type="{http://www.ebi.ac.uk/interpro/resources/schemas/interproscan5}PhobiusLocationType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="profilescan-location" type="{http://www.ebi.ac.uk/interpro/resources/schemas/interproscan5}ProfileScanLocationType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="signalp-location" type="{http://www.ebi.ac.uk/interpro/resources/schemas/interproscan5}SignalPLocationType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="superfamilyhmmer3-location" type="{http://www.ebi.ac.uk/interpro/resources/schemas/interproscan5}SuperFamilyHmmer3LocationType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="tmhmm-location" type="{http://www.ebi.ac.uk/interpro/resources/schemas/interproscan5}TMHMMLocationType" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "locationsType", propOrder = {
    "blastprodomLocation",
    "coilsLocation",
    "fingerprintsLocation",
    "hmmer2Location",
    "hmmer3Location",
    "pantherLocation",
    "patternscanLocation",
    "phobiusLocation",
    "profilescanLocation",
    "signalpLocation",
    "superfamilyhmmer3Location",
    "tmhmmLocation"
})
public class LocationsType {

    @XmlElement(name = "blastprodom-location")
    protected List<BlastProDomLocationType> blastprodomLocation;
    @XmlElement(name = "coils-location")
    protected List<CoilsLocationType> coilsLocation;
    @XmlElement(name = "fingerprints-location")
    protected List<FingerPrintsLocationType> fingerprintsLocation;
    @XmlElement(name = "hmmer2-location")
    protected List<Hmmer2LocationType> hmmer2Location;
    @XmlElement(name = "hmmer3-location")
    protected List<Hmmer3LocationType> hmmer3Location;
    @XmlElement(name = "panther-location")
    protected List<PantherLocationType> pantherLocation;
    @XmlElement(name = "patternscan-location")
    protected List<PatternScanLocationType> patternscanLocation;
    @XmlElement(name = "phobius-location")
    protected List<PhobiusLocationType> phobiusLocation;
    @XmlElement(name = "profilescan-location")
    protected List<ProfileScanLocationType> profilescanLocation;
    @XmlElement(name = "signalp-location")
    protected List<SignalPLocationType> signalpLocation;
    @XmlElement(name = "superfamilyhmmer3-location")
    protected List<SuperFamilyHmmer3LocationType> superfamilyhmmer3Location;
    @XmlElement(name = "tmhmm-location")
    protected List<TMHMMLocationType> tmhmmLocation;

    /**
     * Gets the value of the blastprodomLocation property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the blastprodomLocation property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getBlastprodomLocation().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link BlastProDomLocationType }
     * 
     * 
     */
    public List<BlastProDomLocationType> getBlastprodomLocation() {
        if (blastprodomLocation == null) {
            blastprodomLocation = new ArrayList<BlastProDomLocationType>();
        }
        return this.blastprodomLocation;
    }

    /**
     * Gets the value of the coilsLocation property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the coilsLocation property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCoilsLocation().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CoilsLocationType }
     * 
     * 
     */
    public List<CoilsLocationType> getCoilsLocation() {
        if (coilsLocation == null) {
            coilsLocation = new ArrayList<CoilsLocationType>();
        }
        return this.coilsLocation;
    }

    /**
     * Gets the value of the fingerprintsLocation property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the fingerprintsLocation property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getFingerprintsLocation().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link FingerPrintsLocationType }
     * 
     * 
     */
    public List<FingerPrintsLocationType> getFingerprintsLocation() {
        if (fingerprintsLocation == null) {
            fingerprintsLocation = new ArrayList<FingerPrintsLocationType>();
        }
        return this.fingerprintsLocation;
    }

    /**
     * Gets the value of the hmmer2Location property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the hmmer2Location property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getHmmer2Location().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Hmmer2LocationType }
     * 
     * 
     */
    public List<Hmmer2LocationType> getHmmer2Location() {
        if (hmmer2Location == null) {
            hmmer2Location = new ArrayList<Hmmer2LocationType>();
        }
        return this.hmmer2Location;
    }

    /**
     * Gets the value of the hmmer3Location property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the hmmer3Location property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getHmmer3Location().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Hmmer3LocationType }
     * 
     * 
     */
    public List<Hmmer3LocationType> getHmmer3Location() {
        if (hmmer3Location == null) {
            hmmer3Location = new ArrayList<Hmmer3LocationType>();
        }
        return this.hmmer3Location;
    }

    /**
     * Gets the value of the pantherLocation property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the pantherLocation property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPantherLocation().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link PantherLocationType }
     * 
     * 
     */
    public List<PantherLocationType> getPantherLocation() {
        if (pantherLocation == null) {
            pantherLocation = new ArrayList<PantherLocationType>();
        }
        return this.pantherLocation;
    }

    /**
     * Gets the value of the patternscanLocation property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the patternscanLocation property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPatternscanLocation().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link PatternScanLocationType }
     * 
     * 
     */
    public List<PatternScanLocationType> getPatternscanLocation() {
        if (patternscanLocation == null) {
            patternscanLocation = new ArrayList<PatternScanLocationType>();
        }
        return this.patternscanLocation;
    }

    /**
     * Gets the value of the phobiusLocation property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the phobiusLocation property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPhobiusLocation().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link PhobiusLocationType }
     * 
     * 
     */
    public List<PhobiusLocationType> getPhobiusLocation() {
        if (phobiusLocation == null) {
            phobiusLocation = new ArrayList<PhobiusLocationType>();
        }
        return this.phobiusLocation;
    }

    /**
     * Gets the value of the profilescanLocation property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the profilescanLocation property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getProfilescanLocation().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ProfileScanLocationType }
     * 
     * 
     */
    public List<ProfileScanLocationType> getProfilescanLocation() {
        if (profilescanLocation == null) {
            profilescanLocation = new ArrayList<ProfileScanLocationType>();
        }
        return this.profilescanLocation;
    }

    /**
     * Gets the value of the signalpLocation property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the signalpLocation property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSignalpLocation().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SignalPLocationType }
     * 
     * 
     */
    public List<SignalPLocationType> getSignalpLocation() {
        if (signalpLocation == null) {
            signalpLocation = new ArrayList<SignalPLocationType>();
        }
        return this.signalpLocation;
    }

    /**
     * Gets the value of the superfamilyhmmer3Location property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the superfamilyhmmer3Location property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSuperfamilyhmmer3Location().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SuperFamilyHmmer3LocationType }
     * 
     * 
     */
    public List<SuperFamilyHmmer3LocationType> getSuperfamilyhmmer3Location() {
        if (superfamilyhmmer3Location == null) {
            superfamilyhmmer3Location = new ArrayList<SuperFamilyHmmer3LocationType>();
        }
        return this.superfamilyhmmer3Location;
    }

    /**
     * Gets the value of the tmhmmLocation property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the tmhmmLocation property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTmhmmLocation().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TMHMMLocationType }
     * 
     * 
     */
    public List<TMHMMLocationType> getTmhmmLocation() {
        if (tmhmmLocation == null) {
            tmhmmLocation = new ArrayList<TMHMMLocationType>();
        }
        return this.tmhmmLocation;
    }

}
