//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.03.06 at 01:00:16 PM EST 
//


package uk.ac.ebi.interpro.resources.schemas.interproscan5;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for NucleotideType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="NucleotideType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="sequence" type="{http://www.ebi.ac.uk/interpro/resources/schemas/interproscan5}NucleotideSequenceType" minOccurs="0"/>
 *         &lt;element name="xref" type="{http://www.ebi.ac.uk/interpro/resources/schemas/interproscan5}NucleotideSequenceXrefType" maxOccurs="unbounded"/>
 *         &lt;element ref="{http://www.ebi.ac.uk/interpro/resources/schemas/interproscan5}orf" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "NucleotideType", propOrder = {
    "sequence",
    "xref",
    "orf"
})
public class NucleotideType {

    protected NucleotideSequenceType sequence;
    @XmlElement(required = true)
    protected List<NucleotideSequenceXrefType> xref;
    @XmlElement(required = true)
    protected List<OrfType> orf;

    /**
     * Gets the value of the sequence property.
     * 
     * @return
     *     possible object is
     *     {@link NucleotideSequenceType }
     *     
     */
    public NucleotideSequenceType getSequence() {
        return sequence;
    }

    /**
     * Sets the value of the sequence property.
     * 
     * @param value
     *     allowed object is
     *     {@link NucleotideSequenceType }
     *     
     */
    public void setSequence(NucleotideSequenceType value) {
        this.sequence = value;
    }

    /**
     * Gets the value of the xref property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the xref property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getXref().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link NucleotideSequenceXrefType }
     * 
     * 
     */
    public List<NucleotideSequenceXrefType> getXref() {
        if (xref == null) {
            xref = new ArrayList<NucleotideSequenceXrefType>();
        }
        return this.xref;
    }

    /**
     * Gets the value of the orf property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the orf property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getOrf().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link OrfType }
     * 
     * 
     */
    public List<OrfType> getOrf() {
        if (orf == null) {
            orf = new ArrayList<OrfType>();
        }
        return this.orf;
    }

}
