
package au.edu.unimelb.plantcell.io.ws.interproscan5;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "JDispatcherService", targetNamespace = "http://soap.jdispatcher.ebi.ac.uk", wsdlLocation = "file:/C:/Users/pcbrc.admin/AppData/Local/Temp/tempdir3411339935526925213.tmp/iprscan5_1.wsdl")
public class JDispatcherService_Service
    extends Service
{

    private final static URL JDISPATCHERSERVICE_WSDL_LOCATION;
    private final static WebServiceException JDISPATCHERSERVICE_EXCEPTION;
    private final static QName JDISPATCHERSERVICE_QNAME = new QName("http://soap.jdispatcher.ebi.ac.uk", "JDispatcherService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/C:/Users/pcbrc.admin/AppData/Local/Temp/tempdir3411339935526925213.tmp/iprscan5_1.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        JDISPATCHERSERVICE_WSDL_LOCATION = url;
        JDISPATCHERSERVICE_EXCEPTION = e;
    }

    public JDispatcherService_Service() {
        super(__getWsdlLocation(), JDISPATCHERSERVICE_QNAME);
    }

    public JDispatcherService_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), JDISPATCHERSERVICE_QNAME, features);
    }

    public JDispatcherService_Service(URL wsdlLocation) {
        super(wsdlLocation, JDISPATCHERSERVICE_QNAME);
    }

    public JDispatcherService_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, JDISPATCHERSERVICE_QNAME, features);
    }

    public JDispatcherService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public JDispatcherService_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns JDispatcherService
     */
    @WebEndpoint(name = "JDispatcherServiceHttpPort")
    public JDispatcherService getJDispatcherServiceHttpPort() {
        return super.getPort(new QName("http://soap.jdispatcher.ebi.ac.uk", "JDispatcherServiceHttpPort"), JDispatcherService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns JDispatcherService
     */
    @WebEndpoint(name = "JDispatcherServiceHttpPort")
    public JDispatcherService getJDispatcherServiceHttpPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://soap.jdispatcher.ebi.ac.uk", "JDispatcherServiceHttpPort"), JDispatcherService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (JDISPATCHERSERVICE_EXCEPTION!= null) {
            throw JDISPATCHERSERVICE_EXCEPTION;
        }
        return JDISPATCHERSERVICE_WSDL_LOCATION;
    }

}
