//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.05.30 at 08:19:45 AM EST 
//


package au.edu.unimelb.plantcell.servers.mascotee.jaxb;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the au.edu.unimelb.plantcell.servers.jaxb.mascotee package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _MascotEE_QNAME = new QName("http://www.plantcell.unimelb.edu.au/bioinformatics/ns/MascotEE/v2", "MascotEE");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: au.edu.unimelb.plantcell.servers.jaxb.mascotee
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Search }
     * 
     */
    public Search createSearch() {
        return new Search();
    }

    /**
     * Create an instance of {@link PMFSearch }
     * 
     */
    public PMFSearch createPMFSearch() {
        return new PMFSearch();
    }

    /**
     * Create an instance of {@link MSMSTolerance }
     * 
     */
    public MSMSTolerance createMSMSTolerance() {
        return new MSMSTolerance();
    }

    /**
     * Create an instance of {@link PMFData }
     * 
     */
    public PMFData createPMFData() {
        return new PMFData();
    }

    /**
     * Create an instance of {@link PeptideTolerance }
     * 
     */
    public PeptideTolerance createPeptideTolerance() {
        return new PeptideTolerance();
    }

    /**
     * Create an instance of {@link Data }
     * 
     */
    public Data createData() {
        return new Data();
    }

    /**
     * Create an instance of {@link Identification }
     * 
     */
    public Identification createIdentification() {
        return new Identification();
    }

    /**
     * Create an instance of {@link Quantitation }
     * 
     */
    public Quantitation createQuantitation() {
        return new Quantitation();
    }

    /**
     * Create an instance of {@link Reporting }
     * 
     */
    public Reporting createReporting() {
        return new Reporting();
    }

    /**
     * Create an instance of {@link KeyParameters }
     * 
     */
    public KeyParameters createKeyParameters() {
        return new KeyParameters();
    }

    /**
     * Create an instance of {@link Constraints }
     * 
     */
    public Constraints createConstraints() {
        return new Constraints();
    }

    /**
     * Create an instance of {@link MsMsIonSearch }
     * 
     */
    public MsMsIonSearch createMsMsIonSearch() {
        return new MsMsIonSearch();
    }

    /**
     * Create an instance of {@link SeqQuerySearch }
     * 
     */
    public SeqQuerySearch createSeqQuerySearch() {
        return new SeqQuerySearch();
    }

    /**
     * Create an instance of {@link PMFConstraints }
     * 
     */
    public PMFConstraints createPMFConstraints() {
        return new PMFConstraints();
    }

    /**
     * Create an instance of {@link SeqQuery }
     * 
     */
    public SeqQuery createSeqQuery() {
        return new SeqQuery();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Search }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.plantcell.unimelb.edu.au/bioinformatics/ns/MascotEE/v2", name = "MascotEE")
    public JAXBElement<Search> createMascotEE(Search value) {
        return new JAXBElement<Search>(_MascotEE_QNAME, Search.class, null, value);
    }

}
