
package au.edu.unimelb.plantcell.servers.nectar.targetp;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "TargetPService", targetNamespace = "http://nectar.plantcell.unimelb.edu.au", wsdlLocation = "file:/C:/Users/andrew.cassin/AppData/Local/Temp/tempdir7089719628659291859.tmp/TargetPService_1.wsdl")
public class TargetPService
    extends Service
{

    private final static URL TARGETPSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(au.edu.unimelb.plantcell.servers.nectar.targetp.TargetPService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = au.edu.unimelb.plantcell.servers.nectar.targetp.TargetPService.class.getResource(".");
            url = new URL(baseUrl, "file:/C:/Users/andrew.cassin/AppData/Local/Temp/tempdir7089719628659291859.tmp/TargetPService_1.wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'file:/C:/Users/andrew.cassin/AppData/Local/Temp/tempdir7089719628659291859.tmp/TargetPService_1.wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        TARGETPSERVICE_WSDL_LOCATION = url;
    }

    public TargetPService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public TargetPService() {
        super(TARGETPSERVICE_WSDL_LOCATION, new QName("http://nectar.plantcell.unimelb.edu.au", "TargetPService"));
    }

    /**
     * 
     * @return
     *     returns TargetPServicePortType
     */
    @WebEndpoint(name = "TargetPServiceHttpSoap11Endpoint")
    public TargetPServicePortType getTargetPServiceHttpSoap11Endpoint() {
        return super.getPort(new QName("http://nectar.plantcell.unimelb.edu.au", "TargetPServiceHttpSoap11Endpoint"), TargetPServicePortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns TargetPServicePortType
     */
    @WebEndpoint(name = "TargetPServiceHttpSoap11Endpoint")
    public TargetPServicePortType getTargetPServiceHttpSoap11Endpoint(WebServiceFeature... features) {
        return super.getPort(new QName("http://nectar.plantcell.unimelb.edu.au", "TargetPServiceHttpSoap11Endpoint"), TargetPServicePortType.class, features);
    }

}
