
package compbio.data.msa._01._12._2010;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "AAConWS", targetNamespace = "http://msa.data.compbio/01/12/2010/", wsdlLocation = "file:/C:/Users/andrew.cassin/AppData/Local/Temp/tempdir1057592079064539799.tmp/aacon_1.wsdl")
public class AAConWS
    extends Service
{

    private final static URL AACONWS_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(compbio.data.msa._01._12._2010.AAConWS.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = compbio.data.msa._01._12._2010.AAConWS.class.getResource(".");
            url = new URL(baseUrl, "file:/C:/Users/andrew.cassin/AppData/Local/Temp/tempdir1057592079064539799.tmp/aacon_1.wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'file:/C:/Users/andrew.cassin/AppData/Local/Temp/tempdir1057592079064539799.tmp/aacon_1.wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        AACONWS_WSDL_LOCATION = url;
    }

    public AAConWS(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public AAConWS() {
        super(AACONWS_WSDL_LOCATION, new QName("http://msa.data.compbio/01/12/2010/", "AAConWS"));
    }

    /**
     * 
     * @return
     *     returns SequenceAnnotation
     */
    @WebEndpoint(name = "AAConWSPort")
    public SequenceAnnotation getAAConWSPort() {
        return super.getPort(new QName("http://msa.data.compbio/01/12/2010/", "AAConWSPort"), SequenceAnnotation.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SequenceAnnotation
     */
    @WebEndpoint(name = "AAConWSPort")
    public SequenceAnnotation getAAConWSPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://msa.data.compbio/01/12/2010/", "AAConWSPort"), SequenceAnnotation.class, features);
    }

}
