
package compbio.data.msa._01._12._2010;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebFault(name = "LimitExceededException", targetNamespace = "http://msa.data.compbio/01/12/2010/")
public class LimitExceededException_Exception
    extends Exception
{

    /**
	 * 
	 */
	private static final long serialVersionUID = 220795988676456672L;
	/**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private LimitExceededException faultInfo;

    /**
     * 
     * @param message
     * @param faultInfo
     */
    public LimitExceededException_Exception(String message, LimitExceededException faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param message
     * @param faultInfo
     * @param cause
     */
    public LimitExceededException_Exception(String message, LimitExceededException faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: compbio.data.msa._01._12._2010.LimitExceededException
     */
    public LimitExceededException getFaultInfo() {
        return faultInfo;
    }

}
