
package compbio.data.msa._01._12._2010;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "SequenceAnnotation", targetNamespace = "http://msa.data.compbio/01/12/2010/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface SequenceAnnotation {


    /**
     * 
     * @param jobId
     * @return
     *     returns compbio.data.msa._01._12._2010.ScoreManager
     * @throws ResultNotAvailableException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAnnotation", targetNamespace = "http://msa.data.compbio/01/12/2010/", className = "compbio.data.msa._01._12._2010.GetAnnotation")
    @ResponseWrapper(localName = "getAnnotationResponse", targetNamespace = "http://msa.data.compbio/01/12/2010/", className = "compbio.data.msa._01._12._2010.GetAnnotationResponse")
    public ScoreManager getAnnotation(
        @WebParam(name = "jobId", targetNamespace = "")
        String jobId)
        throws ResultNotAvailableException_Exception
    ;

    /**
     * 
     * @param fastaSequences
     * @return
     *     returns java.lang.String
     * @throws JobSubmissionException_Exception
     * @throws UnsupportedRuntimeException_Exception
     * @throws LimitExceededException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "analize", targetNamespace = "http://msa.data.compbio/01/12/2010/", className = "compbio.data.msa._01._12._2010.Analize")
    @ResponseWrapper(localName = "analizeResponse", targetNamespace = "http://msa.data.compbio/01/12/2010/", className = "compbio.data.msa._01._12._2010.AnalizeResponse")
    public String analize(
        @WebParam(name = "fastaSequences", targetNamespace = "")
        List<FastaSequence> fastaSequences)
        throws JobSubmissionException_Exception, LimitExceededException_Exception, UnsupportedRuntimeException_Exception
    ;

    /**
     * 
     * @param fastaSequences
     * @param options
     * @return
     *     returns java.lang.String
     * @throws JobSubmissionException_Exception
     * @throws WrongParameterException_Exception
     * @throws UnsupportedRuntimeException_Exception
     * @throws LimitExceededException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "customAnalize", targetNamespace = "http://msa.data.compbio/01/12/2010/", className = "compbio.data.msa._01._12._2010.CustomAnalize")
    @ResponseWrapper(localName = "customAnalizeResponse", targetNamespace = "http://msa.data.compbio/01/12/2010/", className = "compbio.data.msa._01._12._2010.CustomAnalizeResponse")
    public String customAnalize(
        @WebParam(name = "fastaSequences", targetNamespace = "")
        List<FastaSequence> fastaSequences,
        @WebParam(name = "options", targetNamespace = "")
        List<Option> options)
        throws JobSubmissionException_Exception, LimitExceededException_Exception, UnsupportedRuntimeException_Exception, WrongParameterException_Exception
    ;

    /**
     * 
     * @param fastaSequences
     * @param preset
     * @return
     *     returns java.lang.String
     * @throws WrongParameterException_Exception
     * @throws JobSubmissionException_Exception
     * @throws UnsupportedRuntimeException_Exception
     * @throws LimitExceededException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "presetAnalize", targetNamespace = "http://msa.data.compbio/01/12/2010/", className = "compbio.data.msa._01._12._2010.PresetAnalize")
    @ResponseWrapper(localName = "presetAnalizeResponse", targetNamespace = "http://msa.data.compbio/01/12/2010/", className = "compbio.data.msa._01._12._2010.PresetAnalizeResponse")
    public String presetAnalize(
        @WebParam(name = "fastaSequences", targetNamespace = "")
        List<FastaSequence> fastaSequences,
        @WebParam(name = "preset", targetNamespace = "")
        Preset preset)
        throws JobSubmissionException_Exception, LimitExceededException_Exception, UnsupportedRuntimeException_Exception, WrongParameterException_Exception
    ;

    /**
     * 
     * @param jobId
     * @return
     *     returns compbio.data.msa._01._12._2010.JobStatus
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getJobStatus", targetNamespace = "http://msa.data.compbio/01/12/2010/", className = "compbio.data.msa._01._12._2010.GetJobStatus")
    @ResponseWrapper(localName = "getJobStatusResponse", targetNamespace = "http://msa.data.compbio/01/12/2010/", className = "compbio.data.msa._01._12._2010.GetJobStatusResponse")
    public JobStatus getJobStatus(
        @WebParam(name = "jobId", targetNamespace = "")
        String jobId);

    /**
     * 
     * @param jobId
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "cancelJob", targetNamespace = "http://msa.data.compbio/01/12/2010/", className = "compbio.data.msa._01._12._2010.CancelJob")
    @ResponseWrapper(localName = "cancelJobResponse", targetNamespace = "http://msa.data.compbio/01/12/2010/", className = "compbio.data.msa._01._12._2010.CancelJobResponse")
    public boolean cancelJob(
        @WebParam(name = "jobId", targetNamespace = "")
        String jobId);

    /**
     * 
     * @param position
     * @param jobId
     * @return
     *     returns compbio.data.msa._01._12._2010.ChunkHolder
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "pullExecStatistics", targetNamespace = "http://msa.data.compbio/01/12/2010/", className = "compbio.data.msa._01._12._2010.PullExecStatistics")
    @ResponseWrapper(localName = "pullExecStatisticsResponse", targetNamespace = "http://msa.data.compbio/01/12/2010/", className = "compbio.data.msa._01._12._2010.PullExecStatisticsResponse")
    public ChunkHolder pullExecStatistics(
        @WebParam(name = "jobId", targetNamespace = "")
        String jobId,
        @WebParam(name = "position", targetNamespace = "")
        long position);

    /**
     * 
     * @return
     *     returns compbio.data.msa._01._12._2010.LimitsManager
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getLimits", targetNamespace = "http://msa.data.compbio/01/12/2010/", className = "compbio.data.msa._01._12._2010.GetLimits")
    @ResponseWrapper(localName = "getLimitsResponse", targetNamespace = "http://msa.data.compbio/01/12/2010/", className = "compbio.data.msa._01._12._2010.GetLimitsResponse")
    public LimitsManager getLimits();

    /**
     * 
     * @param presetName
     * @return
     *     returns compbio.data.msa._01._12._2010.Limit
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getLimit", targetNamespace = "http://msa.data.compbio/01/12/2010/", className = "compbio.data.msa._01._12._2010.GetLimit")
    @ResponseWrapper(localName = "getLimitResponse", targetNamespace = "http://msa.data.compbio/01/12/2010/", className = "compbio.data.msa._01._12._2010.GetLimitResponse")
    public Limit getLimit(
        @WebParam(name = "presetName", targetNamespace = "")
        String presetName);

    /**
     * 
     * @return
     *     returns compbio.data.msa._01._12._2010.RunnerConfig
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getRunnerOptions", targetNamespace = "http://msa.data.compbio/01/12/2010/", className = "compbio.data.msa._01._12._2010.GetRunnerOptions")
    @ResponseWrapper(localName = "getRunnerOptionsResponse", targetNamespace = "http://msa.data.compbio/01/12/2010/", className = "compbio.data.msa._01._12._2010.GetRunnerOptionsResponse")
    public RunnerConfig getRunnerOptions();

    /**
     * 
     * @return
     *     returns compbio.data.msa._01._12._2010.PresetManager
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getPresets", targetNamespace = "http://msa.data.compbio/01/12/2010/", className = "compbio.data.msa._01._12._2010.GetPresets")
    @ResponseWrapper(localName = "getPresetsResponse", targetNamespace = "http://msa.data.compbio/01/12/2010/", className = "compbio.data.msa._01._12._2010.GetPresetsResponse")
    public PresetManager getPresets();

}
