
package dk.dtu.cbs.ws.wstmhmm_2_0b;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.0
 * 
 */
@WebService(name = "WSTMHMM_2_0b", targetNamespace = "http://www.cbs.dtu.dk/ws/WSTMHMM_2_0b")
public interface WSTMHMM20B {


    /**
     * 
     * @param job
     * @return
     *     returns dk.dtu.cbs.ws.ws_common.PollQueueResponse.Queueentry
     */
    @WebMethod(action = "http://www.cbs.dtu.dk/ws/WSTMHMM_2_0b#pollQueue")
    @WebResult(name = "queueentry", targetNamespace = "")
    @RequestWrapper(localName = "pollQueue", targetNamespace = "http://www.cbs.dtu.dk/ws/WSTMHMM_2_0b", className = "dk.dtu.cbs.ws.ws_common.PollQueue")
    @ResponseWrapper(localName = "pollQueueResponse", targetNamespace = "http://www.cbs.dtu.dk/ws/WSTMHMM_2_0b", className = "dk.dtu.cbs.ws.ws_common.PollQueueResponse")
    public dk.dtu.cbs.ws.ws_common.PollQueueResponse.Queueentry pollQueue(
        @WebParam(name = "job", targetNamespace = "")
        dk.dtu.cbs.ws.ws_common.PollQueue.Job job);

    /**
     * 
     * @param parameters
     * @return
     *     returns dk.dtu.cbs.ws.ws_common.RunServiceResponse.Queueentry
     */
    @WebMethod(action = "http://www.cbs.dtu.dk/ws/WSTMHMM_2_0b#runService")
    @WebResult(name = "queueentry", targetNamespace = "")
    @RequestWrapper(localName = "runService", targetNamespace = "http://www.cbs.dtu.dk/ws/WSTMHMM_2_0b", className = "dk.dtu.cbs.ws.ws_tmhmm.RunService")
    @ResponseWrapper(localName = "runServiceResponse", targetNamespace = "http://www.cbs.dtu.dk/ws/WSTMHMM_2_0b", className = "dk.dtu.cbs.ws.ws_common.RunServiceResponse")
    public dk.dtu.cbs.ws.ws_common.RunServiceResponse.Queueentry runService(
        @WebParam(name = "parameters", targetNamespace = "")
        dk.dtu.cbs.ws.ws_tmhmm.RunService.Parameters parameters);

    /**
     * 
     * @param job
     * @return
     *     returns dk.dtu.cbs.ws.ws_tmhmm.FetchResultResponse.Output
     */
    @WebMethod(action = "http://www.cbs.dtu.dk/ws/WSTMHMM_2_0b#fetchResult")
    @WebResult(name = "output", targetNamespace = "")
    @RequestWrapper(localName = "fetchResult", targetNamespace = "http://www.cbs.dtu.dk/ws/WSTMHMM_2_0b", className = "dk.dtu.cbs.ws.ws_common.FetchResult")
    @ResponseWrapper(localName = "fetchResultResponse", targetNamespace = "http://www.cbs.dtu.dk/ws/WSTMHMM_2_0b", className = "dk.dtu.cbs.ws.ws_tmhmm.FetchResultResponse")
    public dk.dtu.cbs.ws.ws_tmhmm.FetchResultResponse.Output fetchResult(
        @WebParam(name = "job", targetNamespace = "")
        dk.dtu.cbs.ws.ws_common.FetchResult.Job job);

}
