//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-558 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.07.06 at 05:50:21 PM EST 
//


package au.edu.unimelb.plantcell.servers.core.jaxb;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the au.edu.unimelb.plantcell.servers.core.jaxb package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _JobMessage_QNAME = new QName("http://www.example.org/JobMessage", "JobMessage");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: au.edu.unimelb.plantcell.servers.core.jaxb
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ResultsType }
     * 
     */
    public ResultsType createResultsType() {
        return new ResultsType();
    }

    /**
     * Create an instance of {@link InputDataType }
     * 
     */
    public InputDataType createInputDataType() {
        return new InputDataType();
    }

    /**
     * Create an instance of {@link FilesType }
     * 
     */
    public FilesType createFilesType() {
        return new FilesType();
    }

    /**
     * Create an instance of {@link JobMessageType }
     * 
     */
    public JobMessageType createJobMessageType() {
        return new JobMessageType();
    }

    /**
     * Create an instance of {@link OutputDataType }
     * 
     */
    public OutputDataType createOutputDataType() {
        return new OutputDataType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link JobMessageType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.example.org/JobMessage", name = "JobMessage")
    public JAXBElement<JobMessageType> createJobMessage(JobMessageType value) {
        return new JAXBElement<JobMessageType>(_JobMessage_QNAME, JobMessageType.class, null, value);
    }

}
